-- DRAFT PREVIEW ONLY · provider=sqlite · contractSetHash=41ac98624962fdd44140016c65c8a5e30cffce35ef68c3eb5dbfae788f9d1352
-- Generated by Prisma Migrate diff from an empty schema, followed by the reviewed provider-invariant overlay.
-- Do not execute without separate migration approval.
-- CreateTable
CREATE TABLE "communications_announcements" (
    "audience_kind" TEXT NOT NULL,
    "author_user_id" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expired_at" DATETIME,
    "id" TEXT NOT NULL PRIMARY KEY,
    "organisation_id" TEXT NOT NULL,
    "published_at" DATETIME,
    "retired_at" DATETIME,
    "scheduled_at" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "title" TEXT NOT NULL,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawn_at" DATETIME,
    "workspace_id" TEXT,
    CONSTRAINT "communications_announcements_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_announcements_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces" ("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_announcements_organisation_id_author_user_id_fkey" FOREIGN KEY ("organisation_id", "author_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_announcements_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_communication_threads" (
    "archived_at" DATETIME,
    "closed_at" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" TEXT NOT NULL,
    "id" TEXT NOT NULL PRIMARY KEY,
    "kind" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "subject" TEXT,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspace_id" TEXT,
    CONSTRAINT "communications_communication_threads_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_communication_threads_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces" ("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_communication_threads_organisation_id_created_by_user_id_fkey" FOREIGN KEY ("organisation_id", "created_by_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_communication_threads_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_direct_message_threads" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" TEXT NOT NULL PRIMARY KEY,
    "organisation_id" TEXT NOT NULL,
    "participant_high_membership_id" TEXT NOT NULL,
    "participant_low_membership_id" TEXT NOT NULL,
    "thread_id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    CONSTRAINT "communications_direct_message_threads_organisation_id_thread_id_workspace_id_fkey" FOREIGN KEY ("organisation_id", "thread_id", "workspace_id") REFERENCES "communications_communication_threads" ("organisation_id", "id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_direct_message_threads_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces" ("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_direct_message_threads_participant_low_membership_id_workspace_id_organisation_id_fkey" FOREIGN KEY ("participant_low_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships" ("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_direct_message_threads_participant_high_membership_id_workspace_id_organisation_id_fkey" FOREIGN KEY ("participant_high_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships" ("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_message_attachments" (
    "byte_length" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" TEXT NOT NULL,
    "deleted_at" DATETIME,
    "file_name" TEXT NOT NULL,
    "id" TEXT NOT NULL PRIMARY KEY,
    "media_type" TEXT NOT NULL,
    "message_id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    CONSTRAINT "communications_message_attachments_organisation_id_message_id_fkey" FOREIGN KEY ("organisation_id", "message_id") REFERENCES "communications_messages" ("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_message_attachments_organisation_id_created_by_user_id_fkey" FOREIGN KEY ("organisation_id", "created_by_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_message_attachments_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_messages" (
    "body" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "edited_at" DATETIME,
    "id" TEXT NOT NULL PRIMARY KEY,
    "organisation_id" TEXT NOT NULL,
    "redacted_at" DATETIME,
    "redacted_by_user_id" TEXT,
    "redaction_reason" TEXT,
    "sender_user_id" TEXT NOT NULL,
    "sequence_number" INTEGER NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'visible',
    "thread_id" TEXT NOT NULL,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "communications_messages_organisation_id_thread_id_fkey" FOREIGN KEY ("organisation_id", "thread_id") REFERENCES "communications_communication_threads" ("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_messages_organisation_id_sender_user_id_fkey" FOREIGN KEY ("organisation_id", "sender_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_messages_redacted_by_user_id_fkey" FOREIGN KEY ("redacted_by_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "communications_messages_sender_user_id_fkey" FOREIGN KEY ("sender_user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_notification_deliveries" (
    "attempt_number" INTEGER NOT NULL,
    "attempted_at" DATETIME,
    "channel" TEXT NOT NULL,
    "completed_at" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "delivered_at" DATETIME,
    "failed_at" DATETIME,
    "failure_code" TEXT,
    "failure_detail" TEXT,
    "id" TEXT NOT NULL PRIMARY KEY,
    "idempotency_key" TEXT NOT NULL,
    "notification_id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "provider_identifier" TEXT,
    "provider_reference" TEXT,
    "response_metadata" JSONB,
    "scheduled_at" DATETIME,
    "sent_at" DATETIME,
    "status" TEXT NOT NULL,
    "terminal_at" DATETIME,
    CONSTRAINT "communications_notification_deliveries_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notification_deliveries_organisation_id_notification_id_fkey" FOREIGN KEY ("organisation_id", "notification_id") REFERENCES "communications_notifications" ("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_notification_preferences" (
    "channel" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "id" TEXT NOT NULL PRIMARY KEY,
    "notification_type" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" TEXT NOT NULL,
    CONSTRAINT "communications_notification_preferences_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notification_preferences_organisation_id_user_id_fkey" FOREIGN KEY ("organisation_id", "user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_notifications" (
    "action_uri" TEXT,
    "actor_user_id" TEXT,
    "body" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dismissed_at" DATETIME,
    "id" TEXT NOT NULL PRIMARY KEY,
    "notification_type" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "read_at" DATETIME,
    "recipient_user_id" TEXT NOT NULL,
    "resource_id" TEXT,
    "resource_type" TEXT,
    "state" TEXT NOT NULL DEFAULT 'unread',
    "title" TEXT NOT NULL,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspace_id" TEXT,
    CONSTRAINT "communications_notifications_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notifications_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "communications_notifications_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces" ("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notifications_organisation_id_recipient_user_id_fkey" FOREIGN KEY ("organisation_id", "recipient_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notifications_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_notifications_organisation_id_actor_user_id_fkey" FOREIGN KEY ("organisation_id", "actor_user_id") REFERENCES "organisation_organisation_memberships" ("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "communications_thread_members" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" TEXT NOT NULL PRIMARY KEY,
    "joined_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_read_at" DATETIME,
    "left_at" DATETIME,
    "organisation_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "thread_id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "workspace_membership_id" TEXT NOT NULL,
    CONSTRAINT "communications_thread_members_organisation_id_thread_id_workspace_id_fkey" FOREIGN KEY ("organisation_id", "thread_id", "workspace_id") REFERENCES "communications_communication_threads" ("organisation_id", "id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "communications_thread_members_workspace_membership_id_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships" ("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "identity_users" (
    "closed_at" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "email" TEXT NOT NULL,
    "email_verified_at" DATETIME,
    "id" TEXT NOT NULL PRIMARY KEY,
    "status" TEXT NOT NULL DEFAULT 'active',
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "organisation_organisation_memberships" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" TEXT NOT NULL PRIMARY KEY,
    "invited_by_user_id" TEXT,
    "joined_at" DATETIME,
    "organisation_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" TEXT NOT NULL,
    CONSTRAINT "organisation_organisation_memberships_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "organisation_organisation_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "organisation_organisation_memberships_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "organisation_organisations" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" TEXT,
    "deleted_at" DATETIME,
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "organisation_organisations_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "organisation_workspace_memberships" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" TEXT NOT NULL PRIMARY KEY,
    "invited_by_user_id" TEXT,
    "joined_at" DATETIME,
    "organisation_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    CONSTRAINT "organisation_workspace_memberships_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces" ("id", "organisation_id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "organisation_workspace_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "organisation_workspace_memberships_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "organisation_workspaces" (
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" TEXT,
    "deleted_at" DATETIME,
    "description" TEXT,
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "organisation_workspaces_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "organisation_workspaces_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);

-- CreateIndex
CREATE INDEX "ix_announcements_1_organisation_id_status_published_at" ON "communications_announcements"("organisation_id", "status", "published_at");

-- CreateIndex
CREATE INDEX "ix_announcements_2_organisation_id_workspace_id" ON "communications_announcements"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_announcements_3_organisation_id_workspace_id_status_published_at" ON "communications_announcements"("organisation_id", "workspace_id", "status", "published_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_1_organisation_id_updated_at" ON "communications_communication_threads"("organisation_id", "updated_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_2_organisation_id_kind_closed_at" ON "communications_communication_threads"("organisation_id", "kind", "closed_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_3_organisation_id_workspace_id" ON "communications_communication_threads"("organisation_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_communication_threads_organisation_id_id" ON "communications_communication_threads"("organisation_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_communication_threads_organisation_id_id_workspace_id" ON "communications_communication_threads"("organisation_id", "id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_direct_message_threads_1_organisation_id_workspace_id" ON "communications_direct_message_threads"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_direct_message_threads_2_organisation_id_workspace_id_participant_low_membership_id_participant_high_membership_id" ON "communications_direct_message_threads"("organisation_id", "workspace_id", "participant_low_membership_id", "participant_high_membership_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_direct_message_threads_organisation_id_workspace_id_participant_low_membership_id_participant_high_membership_id" ON "communications_direct_message_threads"("organisation_id", "workspace_id", "participant_low_membership_id", "participant_high_membership_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_direct_message_threads_organisation_id_id" ON "communications_direct_message_threads"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "ix_message_attachments_1_organisation_id_message_id" ON "communications_message_attachments"("organisation_id", "message_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_message_attachments_organisation_id_storage_key" ON "communications_message_attachments"("organisation_id", "storage_key");

-- CreateIndex
CREATE INDEX "ix_messages_1_organisation_id_thread_id_created_at" ON "communications_messages"("organisation_id", "thread_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_messages_organisation_id_id" ON "communications_messages"("organisation_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_messages_organisation_id_thread_id_sequence_number" ON "communications_messages"("organisation_id", "thread_id", "sequence_number");

-- CreateIndex
CREATE INDEX "ix_notification_deliveries_1_organisation_id_status_scheduled_at" ON "communications_notification_deliveries"("organisation_id", "status", "scheduled_at");

-- CreateIndex
CREATE INDEX "ix_notification_deliveries_2_notification_id_created_at" ON "communications_notification_deliveries"("notification_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_deliveries_organisation_id_idempotency_key" ON "communications_notification_deliveries"("organisation_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_deliveries_notification_id_attempt_number" ON "communications_notification_deliveries"("notification_id", "attempt_number");

-- CreateIndex
CREATE INDEX "ix_notification_preferences_1_organisation_id_user_id" ON "communications_notification_preferences"("organisation_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_preferences_organisation_id_user_id_notification_type_channel" ON "communications_notification_preferences"("organisation_id", "user_id", "notification_type", "channel");

-- CreateIndex
CREATE INDEX "ix_notifications_1_organisation_id_recipient_user_id_created_at" ON "communications_notifications"("organisation_id", "recipient_user_id", "created_at");

-- CreateIndex
CREATE INDEX "ix_notifications_2_organisation_id_recipient_user_id_state" ON "communications_notifications"("organisation_id", "recipient_user_id", "state");

-- CreateIndex
CREATE INDEX "ix_notifications_3_organisation_id_workspace_id" ON "communications_notifications"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_notifications_4_organisation_id_workspace_id_recipient_user_id_created_at" ON "communications_notifications"("organisation_id", "workspace_id", "recipient_user_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notifications_organisation_id_id" ON "communications_notifications"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "ix_thread_members_1_organisation_id_workspace_id_thread_id_workspace_membership_id_left_at" ON "communications_thread_members"("organisation_id", "workspace_id", "thread_id", "workspace_membership_id", "left_at");

-- CreateIndex
CREATE INDEX "ix_thread_members_2_workspace_membership_id_joined_at" ON "communications_thread_members"("workspace_membership_id", "joined_at");

-- CreateIndex
CREATE INDEX "users_status_idx" ON "identity_users"("status");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_unique" ON "identity_users"("email");

-- CreateIndex
CREATE INDEX "organisation_memberships_user_idx" ON "organisation_organisation_memberships"("user_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "organisation_memberships_pair_unique" ON "organisation_organisation_memberships"("organisation_id", "user_id");

-- CreateIndex
CREATE INDEX "organisations_status_idx" ON "organisation_organisations"("status");

-- CreateIndex
CREATE UNIQUE INDEX "organisations_slug_unique" ON "organisation_organisations"("slug");

-- CreateIndex
CREATE INDEX "workspace_memberships_user_status_idx" ON "organisation_workspace_memberships"("user_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_memberships_pair_unique" ON "organisation_workspace_memberships"("workspace_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_memberships_id_workspace_organisation_unique" ON "organisation_workspace_memberships"("id", "workspace_id", "organisation_id");

-- CreateIndex
CREATE INDEX "workspaces_organisation_status_idx" ON "organisation_workspaces"("organisation_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_organisation_slug_unique" ON "organisation_workspaces"("organisation_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_id_organisation_unique" ON "organisation_workspaces"("id", "organisation_id");

-- MAATAA invariant enforcement overlay
-- Migration-only enforcement overlay for approved MAATAA Communications invariants.
-- Append after the generated Prisma schema creates these tables. SQLite cannot
-- add CHECK constraints to existing tables with ALTER TABLE, so equivalent
-- BEFORE triggers enforce inserts and changes to the constrained columns.
-- This file is a preview artifact; it is not an instruction to execute against
-- any database.

CREATE TRIGGER "trg_communications_announcements_audience_scope_insert"
BEFORE INSERT ON "communications_announcements"
WHEN NOT (
  (NEW."audience_kind" = 'ORGANISATION' AND NEW."workspace_id" IS NULL)
  OR
  (NEW."audience_kind" = 'WORKSPACE' AND NEW."workspace_id" IS NOT NULL)
)
BEGIN
  SELECT RAISE(ABORT, 'announcement audience must match workspace scope');
END;

CREATE TRIGGER "trg_communications_announcements_audience_scope_update"
BEFORE UPDATE OF "audience_kind", "workspace_id" ON "communications_announcements"
WHEN NOT (
  (NEW."audience_kind" = 'ORGANISATION' AND NEW."workspace_id" IS NULL)
  OR
  (NEW."audience_kind" = 'WORKSPACE' AND NEW."workspace_id" IS NOT NULL)
)
BEGIN
  SELECT RAISE(ABORT, 'announcement audience must match workspace scope');
END;

CREATE TRIGGER "trg_communications_direct_message_pair_order_insert"
BEFORE INSERT ON "communications_direct_message_threads"
WHEN NOT (
  length(NEW."participant_low_membership_id") = 36
  AND length(replace(NEW."participant_low_membership_id", '-', '')) = 32
  AND substr(NEW."participant_low_membership_id", 9, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 14, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 19, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 24, 1) = '-'
  AND lower(NEW."participant_low_membership_id") NOT GLOB '*[^0-9a-f-]*'
  AND length(NEW."participant_high_membership_id") = 36
  AND length(replace(NEW."participant_high_membership_id", '-', '')) = 32
  AND substr(NEW."participant_high_membership_id", 9, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 14, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 19, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 24, 1) = '-'
  AND lower(NEW."participant_high_membership_id") NOT GLOB '*[^0-9a-f-]*'
  AND lower(NEW."participant_low_membership_id") < lower(NEW."participant_high_membership_id")
)
BEGIN
  SELECT RAISE(ABORT, 'direct-message membership IDs must be strictly ordered');
END;

CREATE TRIGGER "trg_communications_direct_message_pair_order_update"
BEFORE UPDATE OF "participant_low_membership_id", "participant_high_membership_id" ON "communications_direct_message_threads"
WHEN NOT (
  length(NEW."participant_low_membership_id") = 36
  AND length(replace(NEW."participant_low_membership_id", '-', '')) = 32
  AND substr(NEW."participant_low_membership_id", 9, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 14, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 19, 1) = '-'
  AND substr(NEW."participant_low_membership_id", 24, 1) = '-'
  AND lower(NEW."participant_low_membership_id") NOT GLOB '*[^0-9a-f-]*'
  AND length(NEW."participant_high_membership_id") = 36
  AND length(replace(NEW."participant_high_membership_id", '-', '')) = 32
  AND substr(NEW."participant_high_membership_id", 9, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 14, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 19, 1) = '-'
  AND substr(NEW."participant_high_membership_id", 24, 1) = '-'
  AND lower(NEW."participant_high_membership_id") NOT GLOB '*[^0-9a-f-]*'
  AND lower(NEW."participant_low_membership_id") < lower(NEW."participant_high_membership_id")
)
BEGIN
  SELECT RAISE(ABORT, 'direct-message membership IDs must be strictly ordered');
END;

CREATE TRIGGER "trg_communications_direct_message_parent_insert"
BEFORE INSERT ON "communications_direct_message_threads"
WHEN NOT EXISTS (
  SELECT 1
  FROM "communications_communication_threads" AS parent
  WHERE parent."organisation_id" = NEW."organisation_id"
    AND parent."id" = NEW."thread_id"
    AND parent."workspace_id" = NEW."workspace_id"
    AND parent."kind" = 'direct'
)
BEGIN
  SELECT RAISE(ABORT, 'direct-message mapping must reference a direct thread in the same tenant and workspace');
END;

CREATE TRIGGER "trg_communications_direct_message_parent_update"
BEFORE UPDATE OF "organisation_id", "thread_id", "workspace_id" ON "communications_direct_message_threads"
WHEN NOT EXISTS (
  SELECT 1
  FROM "communications_communication_threads" AS parent
  WHERE parent."organisation_id" = NEW."organisation_id"
    AND parent."id" = NEW."thread_id"
    AND parent."workspace_id" = NEW."workspace_id"
    AND parent."kind" = 'direct'
)
BEGIN
  SELECT RAISE(ABORT, 'direct-message mapping must reference a direct thread in the same tenant and workspace');
END;

CREATE TRIGGER "trg_communications_direct_thread_kind_update"
BEFORE UPDATE OF "kind", "workspace_id" ON "communications_communication_threads"
WHEN EXISTS (
  SELECT 1
  FROM "communications_direct_message_threads" AS mapping
  WHERE mapping."organisation_id" = OLD."organisation_id"
    AND mapping."thread_id" = OLD."id"
) AND (NEW."kind" <> 'direct' OR NEW."workspace_id" IS NOT OLD."workspace_id")
BEGIN
  SELECT RAISE(ABORT, 'a mapped direct-message thread must remain direct and in its original workspace');
END;

CREATE TRIGGER "trg_communications_thread_membership_episode_update"
BEFORE UPDATE ON "communications_thread_members"
WHEN OLD."organisation_id" IS NOT NEW."organisation_id"
  OR OLD."workspace_id" IS NOT NEW."workspace_id"
  OR OLD."thread_id" IS NOT NEW."thread_id"
  OR OLD."workspace_membership_id" IS NOT NEW."workspace_membership_id"
  OR OLD."joined_at" IS NOT NEW."joined_at"
  OR OLD."created_at" IS NOT NEW."created_at"
  OR (OLD."left_at" IS NOT NULL AND OLD."left_at" IS NOT NEW."left_at")
BEGIN
  SELECT RAISE(ABORT, 'thread membership episode identity is immutable and ended episodes cannot be reopened or rewritten');
END;

CREATE UNIQUE INDEX "uq_communications_thread_members_active_episode"
  ON "communications_thread_members" (
    "organisation_id",
    "workspace_id",
    "thread_id",
    "workspace_membership_id"
  )
  WHERE "left_at" IS NULL;
