-- DRAFT PREVIEW ONLY · provider=postgresql · contractSetHash=41ac98624962fdd44140016c65c8a5e30cffce35ef68c3eb5dbfae788f9d1352
-- Generated by Prisma Migrate diff from an empty schema, followed by the reviewed provider-invariant overlay.
-- Do not execute without separate migration approval.
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "communications_announcements_audience_kind" AS ENUM ('ORGANISATION', 'WORKSPACE');

-- CreateEnum
CREATE TYPE "communications_announcements_status" AS ENUM ('draft', 'scheduled', 'published', 'expired', 'retired');

-- CreateEnum
CREATE TYPE "communications_communication_threads_kind" AS ENUM ('group', 'direct', 'announcement');

-- CreateEnum
CREATE TYPE "communications_communication_threads_status" AS ENUM ('open', 'closed', 'archived');

-- CreateEnum
CREATE TYPE "communications_messages_state" AS ENUM ('visible', 'redacted');

-- CreateEnum
CREATE TYPE "communications_notification_deliveries_channel" AS ENUM ('in_app', 'email', 'push');

-- CreateEnum
CREATE TYPE "communications_notification_deliveries_status" AS ENUM ('queued', 'sending', 'sent', 'delivered', 'failed', 'suppressed');

-- CreateEnum
CREATE TYPE "communications_notification_preferences_channel" AS ENUM ('in_app', 'email', 'push');

-- CreateEnum
CREATE TYPE "communications_notifications_state" AS ENUM ('unread', 'read', 'dismissed');

-- CreateEnum
CREATE TYPE "communications_thread_members_role" AS ENUM ('member', 'moderator');

-- CreateEnum
CREATE TYPE "identity.users#account_status" AS ENUM ('active', 'disabled', 'closed');

-- CreateEnum
CREATE TYPE "organisation.organisation_memberships#membership_role" AS ENUM ('owner', 'admin', 'member', 'viewer');

-- CreateEnum
CREATE TYPE "organisation.organisation_memberships#membership_status" AS ENUM ('active', 'invited', 'suspended', 'revoked');

-- CreateEnum
CREATE TYPE "organisation.organisations#organisation_status" AS ENUM ('active', 'suspended', 'closed');

-- CreateEnum
CREATE TYPE "organisation.workspace_memberships#membership_status" AS ENUM ('active', 'invited', 'suspended', 'revoked');

-- CreateEnum
CREATE TYPE "organisation.workspace_memberships#workspace_role" AS ENUM ('admin', 'editor', 'viewer');

-- CreateEnum
CREATE TYPE "organisation.workspaces#workspace_status" AS ENUM ('active', 'archived');

-- CreateTable
CREATE TABLE "communications_announcements" (
    "audience_kind" "communications_announcements_audience_kind" NOT NULL,
    "author_user_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expired_at" TIMESTAMPTZ(6),
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "published_at" TIMESTAMPTZ(6),
    "retired_at" TIMESTAMPTZ(6),
    "scheduled_at" TIMESTAMPTZ(6),
    "status" "communications_announcements_status" NOT NULL DEFAULT 'draft',
    "title" VARCHAR(200) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawn_at" TIMESTAMPTZ(6),
    "workspace_id" UUID,

    CONSTRAINT "communications_announcements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_communication_threads" (
    "archived_at" TIMESTAMPTZ(6),
    "closed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" UUID NOT NULL,
    "id" UUID NOT NULL,
    "kind" "communications_communication_threads_kind" NOT NULL,
    "organisation_id" UUID NOT NULL,
    "status" "communications_communication_threads_status" NOT NULL DEFAULT 'open',
    "subject" VARCHAR(200),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspace_id" UUID,

    CONSTRAINT "communications_communication_threads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_direct_message_threads" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "participant_high_membership_id" UUID NOT NULL,
    "participant_low_membership_id" UUID NOT NULL,
    "thread_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,

    CONSTRAINT "communications_direct_message_threads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_message_attachments" (
    "byte_length" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" UUID NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),
    "file_name" VARCHAR(255) NOT NULL,
    "id" UUID NOT NULL,
    "media_type" VARCHAR(200) NOT NULL,
    "message_id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "sha256" VARCHAR(64) NOT NULL,
    "storage_key" VARCHAR(512) NOT NULL,

    CONSTRAINT "communications_message_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_messages" (
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "edited_at" TIMESTAMPTZ(6),
    "id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "redacted_at" TIMESTAMPTZ(6),
    "redacted_by_user_id" UUID,
    "redaction_reason" VARCHAR(500),
    "sender_user_id" UUID NOT NULL,
    "sequence_number" INTEGER NOT NULL,
    "state" "communications_messages_state" NOT NULL DEFAULT 'visible',
    "thread_id" UUID NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "communications_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_notification_deliveries" (
    "attempt_number" INTEGER NOT NULL,
    "attempted_at" TIMESTAMPTZ(6),
    "channel" "communications_notification_deliveries_channel" NOT NULL,
    "completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "delivered_at" TIMESTAMPTZ(6),
    "failed_at" TIMESTAMPTZ(6),
    "failure_code" VARCHAR(100),
    "failure_detail" TEXT,
    "id" UUID NOT NULL,
    "idempotency_key" VARCHAR(200) NOT NULL,
    "notification_id" UUID NOT NULL,
    "organisation_id" UUID NOT NULL,
    "provider_identifier" VARCHAR(160),
    "provider_reference" VARCHAR(255),
    "response_metadata" JSONB,
    "scheduled_at" TIMESTAMPTZ(6),
    "sent_at" TIMESTAMPTZ(6),
    "status" "communications_notification_deliveries_status" NOT NULL,
    "terminal_at" TIMESTAMPTZ(6),

    CONSTRAINT "communications_notification_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_notification_preferences" (
    "channel" "communications_notification_preferences_channel" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "id" UUID NOT NULL,
    "notification_type" VARCHAR(80) NOT NULL,
    "organisation_id" UUID NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" UUID NOT NULL,

    CONSTRAINT "communications_notification_preferences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_notifications" (
    "action_uri" TEXT,
    "actor_user_id" UUID,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dismissed_at" TIMESTAMPTZ(6),
    "id" UUID NOT NULL,
    "notification_type" VARCHAR(80) NOT NULL,
    "organisation_id" UUID NOT NULL,
    "read_at" TIMESTAMPTZ(6),
    "recipient_user_id" UUID NOT NULL,
    "resource_id" VARCHAR(255),
    "resource_type" VARCHAR(100),
    "state" "communications_notifications_state" NOT NULL DEFAULT 'unread',
    "title" VARCHAR(200) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspace_id" UUID,

    CONSTRAINT "communications_notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "communications_thread_members" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" UUID NOT NULL,
    "joined_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_read_at" TIMESTAMPTZ(6),
    "left_at" TIMESTAMPTZ(6),
    "organisation_id" UUID NOT NULL,
    "role" "communications_thread_members_role" NOT NULL,
    "thread_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "workspace_membership_id" UUID NOT NULL,

    CONSTRAINT "communications_thread_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity_users" (
    "closed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "email" VARCHAR(320) NOT NULL,
    "email_verified_at" TIMESTAMPTZ(6),
    "id" UUID NOT NULL,
    "status" "identity.users#account_status" NOT NULL DEFAULT 'active',
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "identity_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organisation_organisation_memberships" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" UUID NOT NULL,
    "invited_by_user_id" UUID,
    "joined_at" TIMESTAMPTZ(6),
    "organisation_id" UUID NOT NULL,
    "role" "organisation.organisation_memberships#membership_role" NOT NULL,
    "status" "organisation.organisation_memberships#membership_status" NOT NULL DEFAULT 'active',
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" UUID NOT NULL,

    CONSTRAINT "organisation_organisation_memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organisation_organisations" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" UUID,
    "deleted_at" TIMESTAMPTZ(6),
    "id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "status" "organisation.organisations#organisation_status" NOT NULL DEFAULT 'active',
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organisation_organisations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organisation_workspace_memberships" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "id" UUID NOT NULL,
    "invited_by_user_id" UUID,
    "joined_at" TIMESTAMPTZ(6),
    "organisation_id" UUID NOT NULL,
    "role" "organisation.workspace_memberships#workspace_role" NOT NULL,
    "status" "organisation.workspace_memberships#membership_status" NOT NULL DEFAULT 'active',
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,

    CONSTRAINT "organisation_workspace_memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organisation_workspaces" (
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_user_id" UUID,
    "deleted_at" TIMESTAMPTZ(6),
    "description" TEXT,
    "id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "organisation_id" UUID NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "status" "organisation.workspaces#workspace_status" NOT NULL DEFAULT 'active',
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organisation_workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ix_announcements_1_organisation_id_status_published_at" ON "communications_announcements"("organisation_id", "status", "published_at");

-- CreateIndex
CREATE INDEX "ix_announcements_2_organisation_id_workspace_id" ON "communications_announcements"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_announcements_3_organisation_id_workspace_id_status_6dbbae6c" ON "communications_announcements"("organisation_id", "workspace_id", "status", "published_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_1_organisation_id_updated_at" ON "communications_communication_threads"("organisation_id", "updated_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_2_organisation_id_kind_closed_at" ON "communications_communication_threads"("organisation_id", "kind", "closed_at");

-- CreateIndex
CREATE INDEX "ix_communication_threads_3_organisation_id_workspace_id" ON "communications_communication_threads"("organisation_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_communication_threads_organisation_id_id" ON "communications_communication_threads"("organisation_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_communication_threads_organisation_id_id_workspace_id" ON "communications_communication_threads"("organisation_id", "id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_direct_message_threads_1_organisation_id_workspace_id" ON "communications_direct_message_threads"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_direct_message_threads_2_organisation_id_workspace__2811225d" ON "communications_direct_message_threads"("organisation_id", "workspace_id", "participant_low_membership_id", "participant_high_membership_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_direct_message_threads_organisation_id_workspace_id_547900c4" ON "communications_direct_message_threads"("organisation_id", "workspace_id", "participant_low_membership_id", "participant_high_membership_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_direct_message_threads_organisation_id_id" ON "communications_direct_message_threads"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "ix_message_attachments_1_organisation_id_message_id" ON "communications_message_attachments"("organisation_id", "message_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_message_attachments_organisation_id_storage_key" ON "communications_message_attachments"("organisation_id", "storage_key");

-- CreateIndex
CREATE INDEX "ix_messages_1_organisation_id_thread_id_created_at" ON "communications_messages"("organisation_id", "thread_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_messages_organisation_id_id" ON "communications_messages"("organisation_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_messages_organisation_id_thread_id_sequence_number" ON "communications_messages"("organisation_id", "thread_id", "sequence_number");

-- CreateIndex
CREATE INDEX "ix_notification_deliveries_1_organisation_id_status_sc_942c17a3" ON "communications_notification_deliveries"("organisation_id", "status", "scheduled_at");

-- CreateIndex
CREATE INDEX "ix_notification_deliveries_2_notification_id_created_at" ON "communications_notification_deliveries"("notification_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_deliveries_organisation_id_idempotency_key" ON "communications_notification_deliveries"("organisation_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_deliveries_notification_id_attempt_number" ON "communications_notification_deliveries"("notification_id", "attempt_number");

-- CreateIndex
CREATE INDEX "ix_notification_preferences_1_organisation_id_user_id" ON "communications_notification_preferences"("organisation_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notification_preferences_organisation_id_user_id_no_2bac9274" ON "communications_notification_preferences"("organisation_id", "user_id", "notification_type", "channel");

-- CreateIndex
CREATE INDEX "ix_notifications_1_organisation_id_recipient_user_id_created_at" ON "communications_notifications"("organisation_id", "recipient_user_id", "created_at");

-- CreateIndex
CREATE INDEX "ix_notifications_2_organisation_id_recipient_user_id_state" ON "communications_notifications"("organisation_id", "recipient_user_id", "state");

-- CreateIndex
CREATE INDEX "ix_notifications_3_organisation_id_workspace_id" ON "communications_notifications"("organisation_id", "workspace_id");

-- CreateIndex
CREATE INDEX "ix_notifications_4_organisation_id_workspace_id_recipi_a285634b" ON "communications_notifications"("organisation_id", "workspace_id", "recipient_user_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "uq_notifications_organisation_id_id" ON "communications_notifications"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "ix_thread_members_1_organisation_id_workspace_id_threa_9c2be101" ON "communications_thread_members"("organisation_id", "workspace_id", "thread_id", "workspace_membership_id", "left_at");

-- CreateIndex
CREATE INDEX "ix_thread_members_2_workspace_membership_id_joined_at" ON "communications_thread_members"("workspace_membership_id", "joined_at");

-- CreateIndex
CREATE INDEX "users_status_idx" ON "identity_users"("status");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_unique" ON "identity_users"("email");

-- CreateIndex
CREATE INDEX "organisation_memberships_user_idx" ON "organisation_organisation_memberships"("user_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "organisation_memberships_pair_unique" ON "organisation_organisation_memberships"("organisation_id", "user_id");

-- CreateIndex
CREATE INDEX "organisations_status_idx" ON "organisation_organisations"("status");

-- CreateIndex
CREATE UNIQUE INDEX "organisations_slug_unique" ON "organisation_organisations"("slug");

-- CreateIndex
CREATE INDEX "workspace_memberships_user_status_idx" ON "organisation_workspace_memberships"("user_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_memberships_pair_unique" ON "organisation_workspace_memberships"("workspace_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_memberships_id_workspace_organisation_unique" ON "organisation_workspace_memberships"("id", "workspace_id", "organisation_id");

-- CreateIndex
CREATE INDEX "workspaces_organisation_status_idx" ON "organisation_workspaces"("organisation_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_organisation_slug_unique" ON "organisation_workspaces"("organisation_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_id_organisation_unique" ON "organisation_workspaces"("id", "organisation_id");

-- AddForeignKey
ALTER TABLE "communications_announcements" ADD CONSTRAINT "communications_announcements_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_announcements" ADD CONSTRAINT "communications_announcements_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces"("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_announcements" ADD CONSTRAINT "communications_announcements_organisation_id_author_user_i_fkey" FOREIGN KEY ("organisation_id", "author_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_announcements" ADD CONSTRAINT "communications_announcements_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_communication_threads" ADD CONSTRAINT "communications_communication_threads_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_communication_threads" ADD CONSTRAINT "communications_communication_threads_workspace_id_organisa_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces"("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_communication_threads" ADD CONSTRAINT "communications_communication_threads_organisation_id_creat_fkey" FOREIGN KEY ("organisation_id", "created_by_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_communication_threads" ADD CONSTRAINT "communications_communication_threads_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_direct_message_threads" ADD CONSTRAINT "communications_direct_message_threads_organisation_id_thre_fkey" FOREIGN KEY ("organisation_id", "thread_id", "workspace_id") REFERENCES "communications_communication_threads"("organisation_id", "id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_direct_message_threads" ADD CONSTRAINT "communications_direct_message_threads_workspace_id_organis_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces"("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_direct_message_threads" ADD CONSTRAINT "communications_direct_message_threads_participant_low_memb_fkey" FOREIGN KEY ("participant_low_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships"("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_direct_message_threads" ADD CONSTRAINT "communications_direct_message_threads_participant_high_mem_fkey" FOREIGN KEY ("participant_high_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships"("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_message_attachments" ADD CONSTRAINT "communications_message_attachments_organisation_id_message_fkey" FOREIGN KEY ("organisation_id", "message_id") REFERENCES "communications_messages"("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_message_attachments" ADD CONSTRAINT "communications_message_attachments_organisation_id_created_fkey" FOREIGN KEY ("organisation_id", "created_by_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_message_attachments" ADD CONSTRAINT "communications_message_attachments_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_messages" ADD CONSTRAINT "communications_messages_organisation_id_thread_id_fkey" FOREIGN KEY ("organisation_id", "thread_id") REFERENCES "communications_communication_threads"("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_messages" ADD CONSTRAINT "communications_messages_organisation_id_sender_user_id_fkey" FOREIGN KEY ("organisation_id", "sender_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_messages" ADD CONSTRAINT "communications_messages_redacted_by_user_id_fkey" FOREIGN KEY ("redacted_by_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_messages" ADD CONSTRAINT "communications_messages_sender_user_id_fkey" FOREIGN KEY ("sender_user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notification_deliveries" ADD CONSTRAINT "communications_notification_deliveries_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notification_deliveries" ADD CONSTRAINT "communications_notification_deliveries_organisation_id_not_fkey" FOREIGN KEY ("organisation_id", "notification_id") REFERENCES "communications_notifications"("organisation_id", "id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notification_preferences" ADD CONSTRAINT "communications_notification_preferences_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notification_preferences" ADD CONSTRAINT "communications_notification_preferences_organisation_id_us_fkey" FOREIGN KEY ("organisation_id", "user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notification_preferences" ADD CONSTRAINT "communications_notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_workspace_id_organisation_id_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces"("id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_organisation_id_recipient_use_fkey" FOREIGN KEY ("organisation_id", "recipient_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_notifications" ADD CONSTRAINT "communications_notifications_organisation_id_actor_user_id_fkey" FOREIGN KEY ("organisation_id", "actor_user_id") REFERENCES "organisation_organisation_memberships"("organisation_id", "user_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_thread_members" ADD CONSTRAINT "communications_thread_members_organisation_id_thread_id_wo_fkey" FOREIGN KEY ("organisation_id", "thread_id", "workspace_id") REFERENCES "communications_communication_threads"("organisation_id", "id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "communications_thread_members" ADD CONSTRAINT "communications_thread_members_workspace_membership_id_work_fkey" FOREIGN KEY ("workspace_membership_id", "workspace_id", "organisation_id") REFERENCES "organisation_workspace_memberships"("id", "workspace_id", "organisation_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_organisation_memberships" ADD CONSTRAINT "organisation_organisation_memberships_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_organisation_memberships" ADD CONSTRAINT "organisation_organisation_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_organisation_memberships" ADD CONSTRAINT "organisation_organisation_memberships_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_organisations" ADD CONSTRAINT "organisation_organisations_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_workspace_memberships" ADD CONSTRAINT "organisation_workspace_memberships_workspace_id_organisati_fkey" FOREIGN KEY ("workspace_id", "organisation_id") REFERENCES "organisation_workspaces"("id", "organisation_id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_workspace_memberships" ADD CONSTRAINT "organisation_workspace_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_workspace_memberships" ADD CONSTRAINT "organisation_workspace_memberships_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_workspaces" ADD CONSTRAINT "organisation_workspaces_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "organisation_organisations"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "organisation_workspaces" ADD CONSTRAINT "organisation_workspaces_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "identity_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- MAATAA invariant enforcement overlay
-- Migration-only enforcement overlay for approved MAATAA Communications invariants.
-- Apply after the generated Prisma schema creates these tables. This file is a
-- preview artifact; it is not an instruction to execute against any database.

ALTER TABLE "communications_announcements"
  ADD CONSTRAINT "ck_communications_announcements_audience_scope"
  CHECK (
    ("audience_kind" = 'ORGANISATION' AND "workspace_id" IS NULL)
    OR
    ("audience_kind" = 'WORKSPACE' AND "workspace_id" IS NOT NULL)
  );

ALTER TABLE "communications_direct_message_threads"
  ADD CONSTRAINT "ck_communications_direct_message_pair_order"
  CHECK ("participant_low_membership_id" < "participant_high_membership_id");

CREATE OR REPLACE FUNCTION "enforce_communications_direct_message_parent"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM "communications_communication_threads" AS parent
    WHERE parent."organisation_id" = NEW."organisation_id"
      AND parent."id" = NEW."thread_id"
      AND parent."workspace_id" = NEW."workspace_id"
      AND parent."kind" = 'direct'
  ) THEN
    RAISE EXCEPTION 'direct-message mapping must reference a direct thread in the same tenant and workspace'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_communications_direct_message_parent_insert"
  BEFORE INSERT ON "communications_direct_message_threads"
  FOR EACH ROW EXECUTE FUNCTION "enforce_communications_direct_message_parent"();

CREATE TRIGGER "trg_communications_direct_message_parent_update"
  BEFORE UPDATE OF "organisation_id", "thread_id", "workspace_id"
  ON "communications_direct_message_threads"
  FOR EACH ROW EXECUTE FUNCTION "enforce_communications_direct_message_parent"();

CREATE OR REPLACE FUNCTION "enforce_communications_direct_thread_kind"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "communications_direct_message_threads" AS mapping
    WHERE mapping."organisation_id" = OLD."organisation_id"
      AND mapping."thread_id" = OLD."id"
  ) AND (NEW."kind" <> 'direct' OR NEW."workspace_id" IS DISTINCT FROM OLD."workspace_id") THEN
    RAISE EXCEPTION 'a mapped direct-message thread must remain direct and in its original workspace'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_communications_direct_thread_kind_update"
  BEFORE UPDATE OF "kind", "workspace_id"
  ON "communications_communication_threads"
  FOR EACH ROW EXECUTE FUNCTION "enforce_communications_direct_thread_kind"();

CREATE UNIQUE INDEX "uq_communications_thread_members_active_episode"
  ON "communications_thread_members" (
    "organisation_id",
    "workspace_id",
    "thread_id",
    "workspace_membership_id"
  )
  WHERE "left_at" IS NULL;

CREATE OR REPLACE FUNCTION "enforce_communications_thread_membership_episode"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD."organisation_id" IS DISTINCT FROM NEW."organisation_id"
    OR OLD."workspace_id" IS DISTINCT FROM NEW."workspace_id"
    OR OLD."thread_id" IS DISTINCT FROM NEW."thread_id"
    OR OLD."workspace_membership_id" IS DISTINCT FROM NEW."workspace_membership_id"
    OR OLD."joined_at" IS DISTINCT FROM NEW."joined_at"
    OR OLD."created_at" IS DISTINCT FROM NEW."created_at"
    OR (OLD."left_at" IS NOT NULL AND NEW."left_at" IS DISTINCT FROM OLD."left_at") THEN
    RAISE EXCEPTION 'thread membership episode identity is immutable and ended episodes cannot be reopened or rewritten'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_communications_thread_membership_episode_update"
  BEFORE UPDATE ON "communications_thread_members"
  FOR EACH ROW EXECUTE FUNCTION "enforce_communications_thread_membership_episode"();
