import { actionButton, avatar, escapeHtml, icon, pageHeading, panel, progress, stat, tag, table } from "../shared.mjs";

export function renderProfile({ session }) {
  const user = session?.user ?? { name: "Maya Chen", email: "maya@example.test", role: "Workspace administrator" };
  return `${pageHeading("Profile", "Keep your personal details and preferences up to date.", `<button class="button button-primary" type="submit" form="profile-form">Save changes</button>`)}<div class="sample-banner">${tag(session ? "HOST SESSION" : "PREVIEW PROFILE", "sand")} ${session ? "Identity details come from your host authentication adapter." : "Example profile; changes are local to this preview."}</div><div class="profile-layout"><div>${panel("Personal information", `<form id="profile-form" class="form-grid" data-form="profile"><div class="profile-avatar-row">${avatar(user.name ?? "Maya Chen", "clay")}<div><strong>Profile photo</strong><small>Image uploads require a connected profile service.</small></div><button class="button button-secondary" type="button" data-action="toast" data-message="Connect a profile service to change your photo">Change photo</button></div><label>Full name<input name="name" value="${escapeHtml(user.name ?? "Maya Chen")}" autocomplete="name" required/></label><label>Email address<input name="email" type="email" value="${escapeHtml(user.email ?? "maya@example.test")}" autocomplete="email" required/></label><label>Role<input value="${escapeHtml(user.role ?? "Workspace member")}" readonly/></label><label>About<textarea name="about" rows="3" placeholder="A little about your work…"></textarea></label></form>`)}${panel("Preferences", `<div class="preference-row"><div><strong>Weekly digest</strong><small>A Friday summary of workspace activity</small></div><label class="switch"><input type="checkbox" checked aria-label="Weekly digest"/><span></span></label></div><div class="preference-row"><div><strong>Product updates</strong><small>News about changes to your tools</small></div><label class="switch"><input type="checkbox" aria-label="Product updates"/><span></span></label></div>`)}</div><aside>${panel("Account security", `<div class="security-line">${tag("JWT", "sage")}<strong>Authentication provided by host</strong></div><p class="muted">Tokens are not stored by this template. Your host manages sign-in, refresh, and protected requests.</p><button class="button button-secondary" data-route="auth/sign-in">Authentication pages</button>`)}${panel("Your workspace", `<div class="profile-workspace">${avatar("MA", "sand")}<div><strong>Maataa Studio</strong><small>Sample workspace</small></div></div><a class="text-link" data-route="projects" href="#projects">View workspace</a>`)}</aside></div>`;
}

const authCopy = {
  "auth/sign-in": ["Welcome back", "Sign in through your organization’s identity service.", "Sign in", ["Email address", "Password"], "Sign in"],
  "auth/sign-up": ["Create an account", "Ask your workspace provider to create your account.", "Create account", ["Full name", "Work email", "Password"], "Create account"],
  "auth/forgot-password": ["Forgot your password?", "We’ll send a reset link if your account is eligible.", "Request reset link", ["Work email"], "Send reset link"],
  "auth/reset-password": ["Choose a new password", "Your identity provider verifies the reset link.", "Reset password", ["New password", "Confirm password"], "Save new password"],
  "auth/unlock-session": ["Unlock your session", "Verify your identity with your organization’s sign-in service.", "Unlock session", ["Work email", "Password"], "Unlock session"],
  "auth/confirmation-required": ["Check your inbox", "Confirm your email address to continue.", "Resend confirmation", ["Work email"], "Resend email"],
};

export function renderAuth(screen, { session }) {
  if (screen === "auth/sign-out") {
    return `<section class="auth-screen"><div class="auth-panel"><div class="auth-brand">${"M"}</div><h1>Sign out</h1><p>${session ? `You’re signed in as ${escapeHtml(session.user?.email ?? "your account")}.` : "You are not signed in to an authentication service."}</p><button class="button button-primary button-wide" data-action="sign-out">Sign out</button><button class="button button-quiet button-wide" data-route="analytics">Return to workspace</button></div></section>`;
  }
  const [title, description, adapterMethod, fields, submitLabel] = authCopy[screen] ?? authCopy["auth/sign-in"];
  return `<section class="auth-screen"><div class="auth-panel"><div class="auth-brand">${"M"}</div><p class="eyebrow-text">MAATAA WORKSPACE</p><h1>${title}</h1><p>${description}</p><form class="auth-form" data-form="auth" data-auth-method="${adapterMethod}">${fields.map((field) => `<label>${field}<input name="${field.toLowerCase().replaceAll(" ", "-")}" type="${field.toLowerCase().includes("password") ? "password" : field.toLowerCase().includes("email") ? "email" : "text"}" autocomplete="${field.toLowerCase().includes("password") ? "current-password" : field.toLowerCase().includes("email") ? "email" : "name"}" required/></label>`).join("")}${screen === "auth/sign-in" ? `<div class="auth-aux"><label><input name="remember" type="checkbox"/> Keep me signed in</label><a data-route="auth/forgot-password" href="#forgot-password">Forgot password?</a></div>` : ""}<button class="button button-primary button-wide" type="submit">${submitLabel}</button></form><div class="auth-disclaimer">JWT is delegated to a host adapter. This template never creates a token or stores one in browser storage.</div>${screen === "auth/sign-in" ? `<p class="auth-switch">New to this workspace? <a data-route="auth/sign-up" href="#sign-up">Create an account</a></p>` : `<p class="auth-switch"><a data-route="auth/sign-in" href="#sign-in">Back to sign in</a></p>`}</div></section>`;
}

export function renderSystemPage(screen) {
  if (screen.startsWith("pricing/")) return renderPricing(screen);
  if (screen.startsWith("invoice/")) return renderInvoice(screen);
  if (screen === "coming-soon") return `<section class="system-hero"><span class="system-icon">${icon("spark", 28)}</span><h1>Something useful is on its way.</h1><p>We’re preparing a new workspace experience. You can keep working in the meantime.</p><div class="coming-progress"><span></span></div><small>Next update · When it is ready</small><button class="button button-primary" data-route="analytics">Return to workspace</button></section>`;
  if (screen === "maintenance") return `<section class="system-hero"><span class="system-icon">${icon("tool", 26)}</span><h1>We’ll be right back.</h1><p>This page is in maintenance preview. Connect a status service to show live incident updates.</p><div class="maintenance-status"><span class="status-pulse"></span><div><strong>Maintenance preview</strong><small>No live status provider connected</small></div>${tag("PREVIEW", "sand")}</div><button class="button button-secondary" data-action="retry-page">Check again</button></section>`;
  if (screen === "error/404" || screen === "error/500") {
    const isNotFound = screen.endsWith("404");
    return `<section class="system-hero error-hero"><div class="error-code">${isNotFound ? "404" : "500"}</div><h1>${isNotFound ? "This page wandered off." : "The page hit a snag."}</h1><p>${isNotFound ? "The link may be old, or the page may have moved." : "Your work is safe in this preview. Try again or head back to the workspace."}</p><div class="heading-actions"><button class="button button-primary" data-route="analytics">Go to dashboard</button>${isNotFound ? "" : `<button class="button button-secondary" data-action="retry-page">Try again</button>`}</div><small>Error page example · No request was sent</small></section>`;
  }
  if (screen === "starter") return `${pageHeading("Skeleton project", "A clean starting point for a host application.", `<button class="button button-primary" data-action="download-skeleton">Download starter notes</button>`)}<div class="sample-banner">${tag("TEMPLATE SOURCE", "sand")} The current app folder is the runnable static skeleton.</div><div class="starter-grid"><div>${panel("Included", `<ul class="starter-list"><li><span>✓</span>Single workspace shell and route map</li><li><span>✓</span>Dynamic screen chunks and loading state</li><li><span>✓</span>Layout, theme, language, and RTL settings</li><li><span>✓</span>Host JWT and permission adapter seams</li><li><span>✓</span>Responsive styles with keyboard support</li><li><span>✓</span>ESLint and Prettier configuration</li></ul>`)}</div><aside>${panel("Connect your services", `<div class="code-sample"><small>AUTH ADAPTER</small><pre>window.MAATAA_ADMIN_AUTH = {\n  signIn: async (credentials) =>\n    api.login(credentials),\n  signOut: async () => api.logout()\n};</pre></div><div class="code-sample"><small>PERMISSION ADAPTER</small><pre>window.MAATAA_ADMIN = {\n  permissions: ["projects:read"]\n};</pre></div>`)}</aside></div><h2 class="section-title">Available content layouts</h2><div class="layout-directory">${["Balanced overview", "Two-column cards", "Three-column cards", "Four-column cards", "Wide detail split", "Equal detail split", "Narrow detail split", "Dense list", "Spacious list", "Compact table", "Comfortable table", "Activity timeline", "Kanban lanes", "Three-up gallery", "Four-up gallery", "Left feature mosaic", "Right feature mosaic", "Chart first", "Metrics first", "Detail rail left", "Detail rail right", "Week planner", "Month planner", "Single focus"].map((name, i) => `<span>${String(i + 1).padStart(2, "0")} · ${name}</span>`).join("")}</div>`;
  return "";
}

function renderInvoice(screen) {
  const modern = screen.endsWith("modern");
  const lineRows = [["Workspace planning workshop", "2 days", "$950.00"], ["Design review facilitation", "1 day", "$600.00"], ["Research synthesis", "1 package", "$420.00"]];
  return `${pageHeading(`Invoice · ${modern ? "Modern" : "Compact"}`, "A printable invoice layout example.", `<button class="button button-secondary no-print" data-action="print-invoice">Print invoice</button>`)}<div class="sample-banner no-print">${tag("SAMPLE DOCUMENT", "sand")} This invoice is illustrative and is not a payment request.</div><article class="invoice-paper ${modern ? "invoice-modern" : "invoice-compact"}"><header class="invoice-header"><div><span class="invoice-brand">M</span><strong>MAATAA STUDIO</strong><small>Workspace services</small></div><div class="invoice-title"><span>INVOICE</span><strong>INV-2026-014</strong><small>Issued Oct 02, 2026</small></div></header><div class="invoice-parties"><div><small>PREPARED FOR</small><strong>Northstar Collective</strong><span>85 Market Street<br/>San Francisco, CA 94103</span></div><div><small>PAYMENT DETAILS</small><strong>Due Oct 16, 2026</strong><span>Example only · No payment method connected</span></div></div>${table(["Description", "Quantity", "Amount"], lineRows.map((row) => row.map((item) => item)))}<div class="invoice-totals"><div><span>Subtotal</span><strong>$1,970.00</strong></div><div><span>Tax</span><strong>$157.60</strong></div><div class="invoice-total"><span>Total</span><strong>$2,127.60</strong></div></div><footer>Thank you for working with us. Sample invoice for layout preview.</footer></article>`;
}

function renderPricing(screen) {
  const variant = screen.split("/")[1];
  const plans = [["Starter", "$0", "For small teams getting organized", ["Up to 3 projects", "Basic dashboards", "Shared workspace"]], ["Studio", "$24", "For teams building momentum", ["Unlimited projects", "Team analytics", "Priority support"]], ["Scale", "Let’s talk", "For complex organizations", ["Advanced access controls", "Custom integrations", "Dedicated support"]]];
  if (variant === "single") return `${pageHeading("Pricing · Single", "A clear plan for one focused team.")}<div class="sample-banner">${tag("EXAMPLE PRICING", "sand")} Rates are illustrative and are not a live offer.</div><div class="pricing-single">${planCard(plans[1], true)}</div>`;
  if (variant === "table") return `${pageHeading("Pricing · Table", "Compare what each workspace plan includes.")}<div class="sample-banner">${tag("EXAMPLE PRICING", "sand")} Plans and rates are illustrative.</div><div class="panel pricing-table">${table(["Included", "Starter", "Studio", "Scale"], [["Projects", "3", "Unlimited", "Unlimited"], ["Team analytics", "Basic", "Advanced", "Advanced"], ["Access controls", "Standard", "Advanced", "Custom"], ["Support", "Community", "Priority", "Dedicated"], ["Integrations", "—", "Included", "Custom"]])}</div>`;
  return `${pageHeading(`Pricing · ${variant === "simple" ? "Simple" : "Modern"}`, "Choose a plan that fits the way your team works.")}<div class="sample-banner">${tag("EXAMPLE PRICING", "sand")} Plans and rates are illustrative, not a published offer.</div><div class="pricing-grid">${plans.map((plan, i) => planCard(plan, i === 1)).join("")}</div>`;
}

function planCard([name, price, description, features], featured = false) {
  return `<article class="plan-card ${featured ? "plan-featured" : ""}">${featured ? tag("POPULAR", "sage") : ""}<h2>${name}</h2><p>${description}</p><div class="plan-price">${price}${price.startsWith("$") ? `<small> / member / month</small>` : ""}</div><ul>${features.map((feature) => `<li>✓ <span>${feature}</span></li>`).join("")}</ul><button class="button ${featured ? "button-primary" : "button-secondary"} button-wide" data-action="choose-plan" data-value="${name}">Choose ${name}</button></article>`;
}
