import { actionButton, avatar, emptyState, escapeHtml, icon, pageHeading, panel, progress, stat, tag, table } from "../shared.mjs";
import { renderKnowledgeExplorer, renderSupport } from "./tlps-knowledge.mjs";

export async function renderAcademy() {
  const courses = [["Leading focused teams", "People practice", 68, "clay", "6 lessons"], ["Planning a healthy sprint", "Project delivery", 35, "sage", "4 lessons"], ["Designing accessible services", "Product craft", 82, "blue", "8 lessons"]];
  return `${pageHeading("Academy", "Small lessons for the work your teams do every day.", actionButton("Browse TLPS guides", "browse-courses", { iconName: "book", variant: "secondary" }))}<div class="sample-banner">${tag("LEARNING PREVIEW", "sand")} Progress is example content and is not tied to a learning account.</div><div class="metric-grid">${stat("In progress", "3", "Across 2 learning paths")}${stat("Completed", "8", "This quarter")}${stat("Team learning hours", "42", "Example total")}</div><div class="course-grid">${courses.map(([title, category, value, tone, lessons]) => `<article class="course-card"><div class="course-art art-${tone}"><span>${category}</span><span class="course-art-mark">${title.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span></div><div class="course-card-body"><small>${category}</small><h2>${title}</h2><p>${lessons} · Self-paced</p>${progress(value, "Your progress")}<button class="button button-secondary" data-action="open-course">${value === 100 ? "Review course" : "Continue learning"}</button></div></article>`).join("")}</div>${await renderKnowledgeExplorer("academy")}`;
}

export function renderCommerce({ orders, products = [] }) {
  const rows = orders.map((order) => [`<strong>${escapeHtml(order.id)}</strong>`, escapeHtml(order.customer), escapeHtml(order.date), `$${Number(order.amount).toFixed(2)}`, tag(order.status, order.status === "Paid" ? "sage" : order.status === "Pending" ? "sand" : "clay"), `<button class="icon-button" aria-label="Actions for ${escapeHtml(order.id)}" data-action="item-menu">${icon("more")}</button>`]);
  const productRows = products.map((product) => [`<strong>${escapeHtml(product.name)}</strong>`, `$${Number(product.amount).toFixed(2)}`, tag(product.status, product.status === "Published" ? "sage" : "neutral")]);
  return `${pageHeading("E-Commerce", "A sample view of orders and store operations.", actionButton("Add product", "new-product", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("PREVIEW STORE", "sand")} Orders below are examples. No checkout or payment provider is connected.</div><div class="metric-grid">${stat("Gross sales", "$12,840", "+9.8%")}${stat("Orders", "186", "+14 this week")}${stat("Average order", "$69.03", "+$4.20")}${stat("Returns", "4", "Needs review", "down")}</div><div class="filter-row"><button class="filter-chip is-selected">All orders</button><button class="filter-chip" data-action="commerce-filter">Paid</button><button class="filter-chip" data-action="commerce-filter">Pending</button><span class="filter-spacer"></span><label class="field-search">${icon("search")}<input type="search" placeholder="Search orders" aria-label="Search orders" data-search-table/></label></div>${panel("Recent orders", table(["Order", "Customer", "Date", "Total", "Status", ""], rows), `<span class="muted">${orders.length} example orders</span>`)}${panel("Product catalog", table(["Product", "Price", "Status"], productRows), `<span class="muted">${products.length} sample products</span>`)}`;
}

export function renderFiles({ files }) {
  return `${pageHeading("File Manager", "Browse shared project files and useful team documents.", actionButton("Upload file", "open-upload", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("BROWSER PREVIEW", "sand")} Files you add are listed in this page session; no cloud storage is connected.</div><div class="file-toolbar"><div class="breadcrumb">Workspace <span>›</span> Shared files</div><div class="segmented"><button class="is-active">List</button><button data-action="toast" data-message="Grid view selected">Grid</button></div></div><div class="panel">${table(["Name", "Owner", "Modified", "Size", ""], files.map((file) => [`<div class="file-name"><span class="file-kind kind-${escapeHtml(file.kind)}">${escapeHtml(file.kind.toUpperCase())}</span><strong>${escapeHtml(file.name)}</strong></div>`, escapeHtml(file.owner), escapeHtml(file.modified), escapeHtml(file.size), `<button class="icon-button" aria-label="More actions for ${escapeHtml(file.name)}" data-action="item-menu">${icon("more")}</button>`]))}<input id="file-upload" class="sr-only" type="file" multiple/></div><div class="storage-summary"><div><strong>Workspace storage</strong><small>Example usage · 6.4 GB of 20 GB</small></div>${progress(32, "32% used")}</div>`;
}

export async function renderHelp() {
  const questions = [["How do I invite someone to my workspace?", "Ask a workspace administrator to open Contacts and add a teammate."], ["Where can I change my notification settings?", "Use the profile menu and choose Preferences. Notification controls are a preview in this template."], ["Can I connect my own data?", "Yes. Connect your API through the host application; these screens currently use local sample content."], ["How does JWT sign-in work?", "Pass an authentication adapter from your host. This template does not mint or validate tokens."], ["How can I change the layout?", "Open Layout & theme in the upper toolbar to choose navigation, content, colors, language, and direction."]];
  const contactSupport = `<a class="button button-secondary" data-route="support" href="#support">${icon("chat", 16)}<span>Contact support</span></a>`;
  return `${pageHeading("Help Center", "Find an answer in the workspace guide or TLPS workflow library.", contactSupport)}<section class="help-hero"><div><h2>What can we help you with?</h2><p>Start with a common topic or search the complete use-case and flow guides below.</p><div class="help-category-row"><button class="help-category" data-action="knowledge-category" data-value="Public"><strong>Getting started</strong><small>Public discovery and product tours</small></button><button class="help-category" data-action="knowledge-category" data-value="Projects"><strong>Projects & tasks</strong><small>Planning, blockers, and closeout</small></button><button class="help-category" data-action="knowledge-category" data-value="Entry & Security"><strong>Account & access</strong><small>Sign-in and onboarding flows</small></button></div></div><div class="help-mark">${icon("circle-help", 34)}</div></section>${panel("Popular workspace questions", `<div class="faq-list">${questions.map(([question, answer]) => `<details class="faq-item"><summary>${escapeHtml(question)}<span>+</span></summary><p>${escapeHtml(answer)}</p></details>`).join("")}</div>`)}${await renderKnowledgeExplorer("help")}`;
}

export async function renderSupportPage(state) {
  return `${pageHeading("Support", "Capture a clear, traceable issue against a TLPS use case or flow.")}<div class="sample-banner">${tag("LOCAL PREVIEW", "sand")} Requests are saved in this browser only; no support service receives them.</div>${await renderSupport(state)}`;
}
