import { actionButton, avatar, emptyState, escapeHtml, icon, pageHeading, panel, tag, table } from "../shared.mjs";

export function renderMessenger({ selectedConversation = "maya" }) {
  const threads = [
    ["maya", "Maya Chen", "I added the latest feedback to the brief.", "10:42", "clay", 2],
    ["leo", "Leo Park", "That works for the next sprint.", "9:18", "blue", 0],
    ["ari", "Ari Bell", "Can you review the release notes?", "Yesterday", "sage", 1],
    ["sam", "Sam Rivera", "Thanks for sending this over.", "Tue", "gold", 0],
  ];
  const people = { maya: ["Maya Chen", "Here are the points from the customer call.", "Great. I’ll add the two follow-ups to the plan.", "I added the latest feedback to the brief."], leo: ["Leo Park", "The updated sequence is ready to review.", "I’ll take a look before planning.", "That works for the next sprint."], ari: ["Ari Bell", "The notes are in the release folder.", "Found them, thank you.", "Can you review the release notes?"] };
  const [name, ...messages] = people[selectedConversation] ?? people.maya;
  return `${pageHeading("Messenger", "Keep team conversations close to the work.", actionButton("New message", "new-message", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("LOCAL PREVIEW", "sand")} Messages are example content and are not sent to a service.</div><section class="messenger-shell panel"><aside class="conversation-list"><label class="field-search">${icon("search")}<input type="search" placeholder="Find a conversation" aria-label="Find a conversation"/></label>${threads.map(([id, person, preview, time, tone, unread]) => `<button class="conversation ${id === selectedConversation ? "selected" : ""}" data-action="select-conversation" data-value="${escapeHtml(id)}">${avatar(person, tone)}<span class="conversation-copy"><strong>${escapeHtml(person)}</strong><small>${escapeHtml(preview)}</small></span><span class="conversation-meta"><small>${escapeHtml(time)}</small>${unread ? tag(String(unread), "clay") : ""}</span></button>`).join("")}</aside><section class="message-thread"><header class="thread-head">${avatar(name, "clay")}<div><strong>${escapeHtml(name)}</strong><small>Team member · Example profile</small></div><button class="icon-button" aria-label="Conversation details" data-action="toast" data-message="Conversation details">${icon("more")}</button></header><div class="message-history"><p class="day-divider">Today</p>${messages.map((message, i) => `<div class="message ${i % 2 ? "message-own" : ""}"><p>${escapeHtml(message)}</p><small>${i === 2 ? "10:42 AM" : "9:16 AM"}</small></div>`).join("")}</div><form class="compose-row" data-form="message"><label class="sr-only" for="message-input">Write a message</label><input id="message-input" name="message" placeholder="Write a message…" required/><button class="button button-primary" type="submit">Send ${icon("arrow", 15)}</button></form></section></section>`;
}

export function renderMailbox({ selectedFolder = "Inbox" }) {
  const emails = [
    ["Elena Morris", "Q4 planning notes", "I pulled together the key points from the team session…", "10:24 AM", true],
    ["Workshop team", "Updated project timeline", "The milestone dates have been adjusted to match…", "9:02 AM", true],
    ["Marcus Lee", "Thanks for the introduction", "Great to meet yesterday. Here’s the follow-up…", "Yesterday", false],
    ["Workspace updates", "Your weekly summary", "A short recap of the activity across your projects…", "Oct 1", false],
  ];
  return `${pageHeading("Mailbox", "A tidy home for the messages that move work forward.", actionButton("Compose", "compose-mail", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("LOCAL PREVIEW", "sand")} Example messages; no email provider is connected.</div><section class="mail-shell panel"><aside class="mail-folders"><button class="folder-tab active">Inbox <b>4</b></button><button class="folder-tab">Starred</button><button class="folder-tab">Sent</button><button class="folder-tab">Drafts</button><button class="folder-tab">Archive</button><div class="folder-label">FOLDERS</div><button class="folder-tab">Project updates</button><button class="folder-tab">Team</button></aside><div class="mail-list">${emails.map(([sender, subject, preview, time, unread], i) => `<button class="mail-item ${i === 0 ? "selected" : ""}" data-action="select-mail"><span class="mail-check"><input type="checkbox" aria-label="Select email from ${escapeHtml(sender)}"/></span><span class="mail-star" aria-label="Star">${icon("star", 15)}</span>${avatar(sender, i % 2 ? "sand" : "clay")}<span class="mail-copy"><strong>${escapeHtml(sender)}${unread ? `<i class="unread-dot"></i>` : ""}</strong><b>${escapeHtml(subject)}</b><small>${escapeHtml(preview)}</small></span><time>${escapeHtml(time)}</time></button>`).join("")}</div><article class="mail-reading"><div class="reading-actions"><button class="icon-button" data-action="toast" data-message="Archived in preview" aria-label="Archive email">${icon("archive")}</button><button class="icon-button" data-action="toast" data-message="Reply is not connected" aria-label="Reply">${icon("reply")}</button><button class="icon-button" data-action="toast" data-message="More message actions" aria-label="More message actions">${icon("more")}</button></div><h2>Q4 planning notes</h2><div class="sender-row">${avatar("Elena Morris", "sage")}<div><strong>Elena Morris</strong><small>elena@example.test · to you</small></div><time>10:24 AM</time></div><div class="email-body"><p>Hi Maya,</p><p>Thanks for facilitating the planning session. I’ve gathered the main themes and next steps so everyone can find them in one place.</p><ul><li>Confirm the product review date</li><li>Share draft goals with each team lead</li><li>Bring open questions to Monday’s planning meeting</li></ul><p>Let me know if I missed anything.</p><p>Elena</p></div><button class="button button-secondary" data-action="toast" data-message="Reply is not connected to an email service">Reply to this message</button></article></section>`;
}

export function renderContacts({ contacts = [["Maya Chen", "maya@example.test", "Product", "Online", "clay"], ["Leo Park", "leo@example.test", "Engineering", "Away", "blue"], ["Ari Bell", "ari@example.test", "Design", "Online", "sage"], ["Sam Rivera", "sam@example.test", "Operations", "Offline", "gold"], ["Nia Patel", "nia@example.test", "Finance", "Online", "sand"]] } = {}) {
  return `${pageHeading("Contacts", "Find the people behind your projects.", actionButton("Add contact", "new-contact", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("PREVIEW DIRECTORY", "sand")} Example contacts only.</div><div class="directory-toolbar"><label class="field-search">${icon("search")}<input type="search" placeholder="Search by name, email, or team" aria-label="Search contacts" data-search-table/></label><div class="segmented"><button class="is-active">All people</button><button data-action="toast" data-message="Team filter selected">Teams</button></div></div>${panel("Workspace directory", table(["Person", "Team", "Email", "Presence", ""], contacts.map(([name, email, team, status, tone]) => [`<div class="person-cell">${avatar(name, tone)}<strong>${escapeHtml(name)}</strong></div>`, escapeHtml(team), escapeHtml(email), tag(status, status === "Online" ? "sage" : "neutral"), `<button class="icon-button" aria-label="More actions for ${escapeHtml(name)}" data-action="item-menu">${icon("more")}</button>`])), `<span class="muted">${contacts.length} people</span>`)}`;
}

export function renderNotifications({ notifications }) {
  return `${pageHeading("Notifications", "Updates that help you decide what to do next.", `<button class="button button-secondary" data-action="mark-all-read">Mark all read</button>`)}<div class="sample-banner">${tag("PREVIEW UPDATES", "sand")} Notifications are generated from sample workspace activity.</div><div class="notification-filters"><button class="filter-chip is-selected">All</button><button class="filter-chip" data-action="notification-filter">Unread</button><button class="filter-chip" data-action="notification-filter">Mentions</button></div><section class="panel notification-list">${notifications.map((item) => `<article class="notification-row ${item.read ? "is-read" : ""}">${avatar(item.name, item.tone)}<div class="notification-copy"><p><strong>${escapeHtml(item.name)}</strong> ${escapeHtml(item.message)}</p><small>${escapeHtml(item.when)} · ${escapeHtml(item.project)}</small></div>${item.read ? "" : `<span class="unread-dot" aria-label="Unread"></span>`}<button class="panel-menu" aria-label="Notification options" data-action="mark-read" data-id="${escapeHtml(item.id)}">${icon("more")}</button></article>`).join("")}</section>`;
}

export function renderNotes({ notes, selectedNote }) {
  const active = notes.find((note) => note.id === selectedNote) ?? notes[0];
  return `${pageHeading("Notes", "Capture decisions and keep helpful details close by.", actionButton("New note", "new-note", { iconName: "plus", variant: "primary" }))}<div class="sample-banner">${tag("LOCAL NOTES", "sand")} Notes are stored in this browser only.</div><section class="notes-shell panel"><aside class="note-list">${notes.map((note) => `<button class="note-item ${note.id === active?.id ? "selected" : ""}" data-action="select-note" data-id="${escapeHtml(note.id)}"><strong>${escapeHtml(note.title || "Untitled note")}</strong><small>${escapeHtml(note.updated)} · ${escapeHtml(note.body.slice(0, 52))}…</small></button>`).join("")}${notes.length ? "" : emptyState("No notes yet", "Create a note to get started.")}</aside>${active ? `<form class="note-editor" data-form="save-note" data-note-id="${escapeHtml(active.id)}"><input name="title" aria-label="Note title" placeholder="Untitled note" value="${escapeHtml(active.title ?? "")}"/><textarea name="body" aria-label="Note content" placeholder="Write a note…">${escapeHtml(active.body ?? "")}</textarea><footer><span class="muted">Saved in this browser</span><button class="button button-primary" type="submit">Save note</button></footer></form>` : emptyState("Choose a note", "Create a note to get started.")}</section>`;
}
