import { actionButton, emptyState, escapeHtml, icon, pageHeading, tag } from "../shared.mjs";
import { capabilityRegistry as capabilities } from "../infrastructure-registry.mjs";

const safeUrl = (value) => {
  try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) && !url.username && !url.password ? url.href : ""; }
  catch { return ""; }
};
const assignmentsForApp = (state, appId) => state.servers.flatMap((server) => (server.environmentAssignments ?? []).filter((assignment) => assignment.appId === appId).map((assignment) => ({ ...assignment, server })));
const applicationName = (state, appId) => state.applications.find((item) => item.id === appId)?.name ?? "Removed application";
const environmentName = (state, appId, environmentId) => state.applications.find((item) => item.id === appId)?.environments.find((item) => item.id === environmentId)?.name ?? "Environment needs review";
const tabButton = (state, id, label, iconName) => `<button class="platform-tab ${state.platformTab === id ? "is-active" : ""}" type="button" role="tab" aria-selected="${state.platformTab === id}" data-action="platform-tab" data-value="${id}">${icon(iconName, 16)}<span>${label}</span></button>`;

function appForm(state) {
  if (state.platformForm !== "application") return "";
  const record = state.applications.find((item) => item.id === state.platformEditingId) ?? {};
  const domains = (record.domains ?? []).map((domain) => domain.hostname).join("\n");
  const routeMappings = (record.domains ?? []).flatMap((domain) => (domain.routeMappings ?? []).map((mapping) => `${domain.hostname} | ${mapping.environmentId ?? domain.environmentId} | ${mapping.path} | ${mapping.routeId}`)).join("\n");
  const environments = (record.environments ?? []).map((environment) => `${environment.id} | ${environment.name}`).join("\n");
  const routes = (record.routes ?? []).map((route) => `${route.id} | ${route.path} | ${route.label} | ${route.group ?? "Pages"}`).join("\n");
  const repository = record.repository ?? {};
  return `<section class="platform-editor" aria-labelledby="platform-editor-title"><header><div><h2 id="platform-editor-title">${record.id ? "Edit application" : "Add application"}</h2><p>Record app ownership details for this browser draft.</p></div><button class="icon-button" type="button" data-action="platform-cancel" aria-label="Close editor">${icon("close")}</button></header>
    <form data-form="platform-config" data-kind="application" data-editing-id="${escapeHtml(record.id ?? "")}" class="platform-form">
      <label>Application name<input name="name" value="${escapeHtml(record.name ?? "")}" autocomplete="off" required maxlength="80" placeholder="e.g. NEVO Events"/></label>
      <label>Short description<input name="description" value="${escapeHtml(record.summary ?? record.description ?? "")}" maxlength="120" placeholder="What this application provides"/></label>
      <div class="platform-form-field"><label>Domains<textarea name="domains" rows="2" placeholder="one domain per line, e.g. app.example.in">${escapeHtml(domains)}</textarea></label><small>Domains are saved as unverified references. This does not change DNS.</small></div>
      <div class="platform-form-field"><label>Environments<textarea name="environments" rows="2" placeholder="preview | Local preview">${escapeHtml(environments)}</textarea></label><small>One environment per line: id | display name.</small></div>
      <details class="platform-field-wide platform-routes-editor"><summary>${(record.routes ?? []).length} app-owned routes and pages</summary><label>Route registry<textarea name="routes" rows="5" spellcheck="false" placeholder="route-id | /path | Page title | Group">${escapeHtml(routes)}</textarea></label><small>One route per line. Changes stay in this browser draft; each route remains owned by this application.</small></details>
      <div class="platform-form-field platform-field-wide"><label>Domain route mappings<textarea name="routeMappings" rows="3" placeholder="app.example.in | preview | / | overview">${escapeHtml(routeMappings)}</textarea></label><small>One mapping per line: domain | environment id | path | route id. Route IDs belong to this application.</small></div>
      <div class="platform-form-field"><label>Git repository URL<input name="repositoryUrl" value="${escapeHtml(repository.url ?? "")}" type="url" inputmode="url" placeholder="https://github.com/team/project"/></label><small>No connection check or Git write is performed.</small></div>
      <label>Default branch<input name="defaultBranch" value="${escapeHtml(repository.defaultBranch ?? "")}" maxlength="120" placeholder="main"/></label>
      <label>Build command<input name="buildCommand" value="${escapeHtml(repository.buildCommand ?? "")}" maxlength="200" placeholder="npm run build"/></label>
      <label>Build output directory<input name="outputDirectory" value="${escapeHtml(repository.outputDirectory ?? "")}" maxlength="160" placeholder="dist"/></label>
      <footer class="platform-field-wide"><button class="button button-quiet" type="button" data-action="platform-cancel">Cancel</button><button class="button button-primary" type="submit">Save local draft</button></footer>
    </form></section>`;
}

function serverForm(state) {
  if (state.platformForm !== "server") return "";
  const record = state.servers.find((item) => item.id === state.platformEditingId) ?? {};
  const selectedCapabilities = new Set(record.capabilities ?? []);
  const assignedEnvironments = new Set((record.environmentAssignments ?? []).map((assignment) => `${assignment.appId}|${assignment.environmentId}`));
  return `<section class="platform-editor" aria-labelledby="platform-editor-title"><header><div><h2 id="platform-editor-title">${record.id ? "Edit server" : "Add server"}</h2><p>Describe a server and the capabilities it offers. No credentials are stored.</p></div><button class="icon-button" type="button" data-action="platform-cancel" aria-label="Close editor">${icon("close")}</button></header>
    <form data-form="platform-config" data-kind="server" data-editing-id="${escapeHtml(record.id ?? "")}" class="platform-form">
      <label>Server name<input name="name" value="${escapeHtml(record.name ?? "")}" autocomplete="off" maxlength="80" required placeholder="e.g. Primary application host"/></label>
      <div class="platform-form-field"><label>Hostname or IP address<input name="host" value="${escapeHtml(record.host ?? "")}" autocomplete="off" spellcheck="false" required placeholder="server.example.in"/></label><small>Do not enter credentials or access tokens.</small></div>
      <label>Provider<input name="provider" value="${escapeHtml(record.provider ?? "")}" maxlength="80" placeholder="Optional provider name"/></label>
      <label>Region<input name="region" value="${escapeHtml(record.region ?? "")}" maxlength="80" placeholder="Optional region"/></label>
      <fieldset class="platform-field-wide"><legend>Capabilities</legend><div class="platform-check-grid">${capabilities.map((item) => `<label class="platform-check"><input type="checkbox" name="capabilities" value="${escapeHtml(item)}" ${selectedCapabilities.has(item) ? "checked" : ""}/><span>${escapeHtml(item)}</span></label>`).join("")}</div></fieldset>
      <fieldset class="platform-field-wide"><legend>Application environments using this server</legend><div class="platform-check-grid">${state.applications.flatMap((item) => item.environments.map((environment) => { const key = `${item.id}|${environment.id}`; return `<label class="platform-check"><input type="checkbox" name="environmentAssignments" value="${escapeHtml(key)}" ${assignedEnvironments.has(key) ? "checked" : ""}/><span>${escapeHtml(item.name)} · ${escapeHtml(environment.name)}</span></label>`; })).join("") || `<p class="platform-field-note">Add an application environment before assigning one.</p>`}</div></fieldset>
      <label>Infrastructure pool label<input name="pool" value="${escapeHtml(record.pool ?? "")}" maxlength="40" placeholder="Optional hosting pool or zone"/></label>
      <footer class="platform-field-wide"><button class="button button-quiet" type="button" data-action="platform-cancel">Cancel</button><button class="button button-primary" type="submit">Save local draft</button></footer>
    </form></section>`;
}

function applicationTable(state) {
  const rows = state.applications.map((item) => {
    const urls = safeUrl(item.repository?.url ?? "");
    const assigned = assignmentsForApp(state, item.id);
    const domainContent = item.domains.length ? item.domains.map((domain) => `<div class="platform-domain"><strong>${escapeHtml(domain.hostname)}</strong>${tag(domain.verification === "verified" ? "VERIFIED" : "UNVERIFIED", domain.verification === "verified" ? "sage" : "gold")}<small>${domain.routeMappings.length} route mapping${domain.routeMappings.length === 1 ? "" : "s"}</small></div>`).join("") : `<span class="platform-secondary">No domain configured</span>`;
    const repoContent = urls ? `<a class="platform-repository" href="${escapeHtml(urls)}" target="_blank" rel="noreferrer">${icon("code", 15)}<span>${escapeHtml(item.repository.url)}</span></a><small>${escapeHtml([item.repository.defaultBranch, item.repository.buildCommand, item.repository.outputDirectory].filter(Boolean).join(" · ") || "Build configuration incomplete")}</small>` : `<div class="platform-empty-value"><strong>Not connected</strong><small>No repository configured</small></div>`;
    const assignedContent = assigned.length ? assigned.map((assignment) => `<span class="platform-server-chip">${icon("server", 13)}${escapeHtml(assignment.server.name)} · ${escapeHtml(environmentName(state, item.id, assignment.environmentId))}</span>`).join("") : `<div class="platform-empty-value"><strong>No server assignments</strong><small>Not assigned to an environment</small></div>`;
    const appMeta = [item.summary || item.description || "Application", `${item.environments.length} environment${item.environments.length === 1 ? "" : "s"}`].join(" · ");
    return `<article class="platform-app-row" role="row"><div class="platform-app-cell platform-app-name" role="cell"><span class="platform-app-mark">${icon("grid", 17)}</span><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(appMeta)}</small></div></div><div class="platform-app-cell platform-app-domains" role="cell"><span class="platform-cell-label">Domains</span>${domainContent}<small>Local draft only</small></div><div class="platform-app-cell platform-app-repo" role="cell"><span class="platform-cell-label">Repository and build</span>${repoContent}</div><div class="platform-app-cell platform-app-servers" role="cell"><span class="platform-cell-label">Environment infrastructure</span>${assignedContent}</div><div class="platform-app-cell platform-app-status" role="cell">${tag("LOCAL PREVIEW", "gold")}<small>Not operationally verified</small></div><div class="platform-row-actions" role="cell"><button class="icon-button" type="button" data-action="platform-edit-app" data-id="${escapeHtml(item.id)}" aria-label="Edit ${escapeHtml(item.name)}">${icon("settings", 15)}</button><button class="icon-button" type="button" data-action="platform-remove-app" data-id="${escapeHtml(item.id)}" aria-label="Remove ${escapeHtml(item.name)}">${icon("close", 15)}</button></div></article>`;
  }).join("");
  return `<div class="platform-table-scroll"><div class="platform-app-table" role="table" aria-label="Application registry"><div class="platform-app-columns" role="row"><span role="columnheader">Application</span><span role="columnheader">Domain</span><span role="columnheader">Repository</span><span role="columnheader">Assigned servers</span><span role="columnheader">Status</span><span role="columnheader">Actions</span></div>${rows || `<div class="platform-table-empty">${emptyState("No applications registered", "Add an application to start mapping domains, repositories, and infrastructure.", actionButton("Add application", "platform-add-app", { variant: "primary" }))}</div>`}</div></div><footer class="platform-table-footer"><span>Showing ${state.applications.length} application${state.applications.length === 1 ? "" : "s"}</span><span>${state.applications.length ? tag(`${state.applications.length} local drafts`, "neutral") : ""}</span></footer>`;
}

function serverInventory(state) {
  if (!state.servers.length) return `<div class="platform-empty-inventory"><span class="platform-empty-icon">${icon("server", 27)}</span><h3>No servers registered yet</h3><p>Add a server to map infrastructure capabilities to the applications that use them.</p>${actionButton("Add server", "platform-add-server", { variant: "primary" })}</div>`;
  return `<div class="platform-server-list">${state.servers.map((server) => `<article class="platform-server-row"><div class="platform-server-primary"><span class="platform-server-mark">${icon("server", 18)}</span><div><strong>${escapeHtml(server.name)}</strong><small>${escapeHtml([server.host, server.provider, server.region, server.pool].filter(Boolean).join(" · "))}</small></div></div><div class="platform-server-capabilities"><span class="platform-cell-label">Capabilities</span><div class="platform-chip-list">${server.capabilities.map((item) => tag(item, "sage")).join("")}</div></div><div class="platform-server-apps"><span class="platform-cell-label">Assigned application environments</span><div class="platform-chip-list">${server.environmentAssignments?.length ? server.environmentAssignments.map((assignment) => tag(`${applicationName(state, assignment.appId)} · ${environmentName(state, assignment.appId, assignment.environmentId)}`, "neutral")).join("") : `<span class="platform-secondary">None assigned</span>`}</div></div><div class="platform-server-status">${tag("LOCAL PREVIEW", "gold")}<small>Connectivity not checked</small></div><div class="platform-row-actions"><button class="icon-button" type="button" data-action="platform-edit-server" data-id="${escapeHtml(server.id)}" aria-label="Edit ${escapeHtml(server.name)}">${icon("settings", 15)}</button><button class="icon-button" type="button" data-action="platform-remove-server" data-id="${escapeHtml(server.id)}" aria-label="Remove ${escapeHtml(server.name)}">${icon("close", 15)}</button></div></article>`).join("")}</div>`;
}

function coveragePanel(state) {
  if (!state.servers.length) return `<section class="platform-panel platform-coverage"><header><div><h2>Service coverage</h2><p>Server allocation across application capabilities.</p></div></header><div class="platform-coverage-empty"><span class="platform-empty-icon">${icon("server", 30)}</span><h3>No servers registered yet</h3><p>Add servers to show which capabilities are available to each application.</p>${actionButton("Add server", "platform-add-server", { variant: "primary" })}</div></section>`;
  const covered = capabilities.map((capability) => ({ capability, assignments: state.servers.flatMap((server) => (server.environmentAssignments ?? []).filter((assignment) => assignment.capabilities.includes(capability)).map((assignment) => ({ server, assignment }))) })).filter((item) => item.assignments.length);
  return `<section class="platform-panel platform-coverage"><header><div><h2>Environment service coverage</h2><p>${covered.length} capability types are assigned to application environments.</p></div></header><div class="platform-coverage-list">${covered.map(({ capability, assignments }) => `<div class="platform-coverage-row"><span>${escapeHtml(capability)}</span><strong>${assignments.length}</strong><small>${assignments.map(({ server, assignment }) => `${escapeHtml(server.name)} → ${escapeHtml(applicationName(state, assignment.appId))} · ${escapeHtml(environmentName(state, assignment.appId, assignment.environmentId))}`).join(", ")}</small></div>`).join("")}</div></section>`;
}

function capabilityMatrix(state) {
  const environments = state.applications.flatMap((application) => application.environments.map((environment) => ({ application, environment })));
  return `<section class="platform-panel"><header><div><h2>Capability assignments</h2><p>Capabilities are assigned to application environments in this browser draft.</p></div><button class="button button-primary" type="button" data-action="platform-add-server">${icon("plus", 15)}<span>Add server</span></button></header>${state.servers.length && environments.length ? `<div class="platform-capability-matrix" style="--app-count:${Math.max(1, environments.length)}"><div class="platform-matrix-row platform-matrix-head"><span>Capability</span>${environments.map(({ application, environment }) => `<strong>${escapeHtml(application.name)} · ${escapeHtml(environment.name)}</strong>`).join("")}</div>${capabilities.map((capability) => {
    const hasAssignment = state.servers.some((server) => (server.environmentAssignments ?? []).some((assignment) => assignment.capabilities.includes(capability)));
    if (!hasAssignment) return "";
    return `<div class="platform-matrix-row"><span>${escapeHtml(capability)}</span>${environments.map(({ application, environment }) => {
      const assigned = state.servers.filter((server) => (server.environmentAssignments ?? []).some((assignment) => assignment.appId === application.id && assignment.environmentId === environment.id && assignment.capabilities.includes(capability)));
      return `<span>${assigned.length ? `${tag(`${assigned.length} server${assigned.length === 1 ? "" : "s"}`, "sage")}<small>${assigned.map((item) => escapeHtml(item.name)).join(", ")}</small>` : `<span class="platform-secondary">—</span>`}</span>`;
    }).join("")}</div>`;
  }).join("")}</div>` : `<div class="platform-empty-inventory"><span class="platform-empty-icon">${icon("grid", 27)}</span><h3>No capability assignments yet</h3><p>Register a server, define an application environment, and assign capabilities.</p>${actionButton("Add server", "platform-add-server", { variant: "primary" })}</div>`}</section>`;
}

export function renderPlatform(state) {
  const appCount = state.applications.length;
  const serverCount = state.servers.length;
  const headingAction = state.platformTab === "apps" ? actionButton("Add application", "platform-add-app", { variant: "primary" }) : actionButton("Add server", "platform-add-server", { variant: "primary" });
  const heading = pageHeading("Applications and Infrastructure", "Configure application domains and repositories, and assign servers to capabilities.", headingAction);
  const disclosure = `<div class="platform-boundary"><span class="platform-local-badge">${icon("lock", 12)} LOCAL DRAFT</span><span class="platform-boundary-separator"></span><strong>NO INFRASTRUCTURE WRITES</strong><span>Changes are saved in this browser only. DNS, Git, and servers are not contacted.</span></div>`;
  const navigation = `<nav class="platform-subnav" aria-label="Platform sections"><a href="#overview" data-route="overview">${icon("grid", 15)}<span>Workspace overview</span></a><button class="${state.platformTab === "apps" ? "is-current" : ""}" type="button" data-action="platform-tab" data-value="apps" ${state.platformTab === "apps" ? 'aria-current="page"' : ""}>${icon("chart", 15)}<span>Applications</span></button><button class="${state.platformTab === "servers" ? "is-current" : ""}" type="button" data-action="platform-tab" data-value="servers" ${state.platformTab === "servers" ? 'aria-current="page"' : ""}>${icon("server", 15)}<span>Infrastructure</span></button><button class="${state.platformTab === "capabilities" ? "is-current" : ""}" type="button" data-action="platform-tab" data-value="capabilities" ${state.platformTab === "capabilities" ? 'aria-current="page"' : ""}>${icon("pulse", 15)}<span>Capabilities</span></button><button type="button" data-action="toast" data-message="Deployment records are not connected in this local preview.">${icon("arrow", 15)}<span>Deployments</span></button><button type="button" data-action="toast" data-message="No activity service is connected.">${icon("note", 15)}<span>Activity log</span></button></nav>`;
  const tabs = `<div class="platform-tabs" role="tablist" aria-label="Infrastructure views">${tabButton(state, "apps", "Applications", "grid")}${tabButton(state, "servers", "Servers", "server")}${tabButton(state, "capabilities", "Capabilities", "settings")}<span class="platform-tab-spacer"></span><span class="platform-tab-count">${appCount} apps · ${serverCount} servers</span></div>`;
  let body = "";
  if (state.platformTab === "apps") {
    body = `<div class="platform-overview-grid"><section class="platform-panel platform-registry"><header><div><h2>Application registry</h2><p>Manage domains, repositories, and infrastructure assignments.</p></div><label class="platform-search">${icon("search", 15)}<input type="search" placeholder="Search applications" aria-label="Search applications" data-platform-filter/></label></header>${applicationTable(state)}</section>${coveragePanel(state)}<section class="platform-panel platform-inventory"><header><div><h2>Server capability inventory</h2><p>Register servers and map the services used by your applications.</p></div>${actionButton("Add server", "platform-add-server", { variant: "quiet" })}</header>${serverInventory(state)}</section></div>`;
  } else if (state.platformTab === "servers") {
    body = `<section class="platform-panel"><header><div><h2>Server inventory</h2><p>Server endpoints and capabilities saved in the local preview.</p></div>${actionButton("Add server", "platform-add-server", { variant: "primary" })}</header>${serverInventory(state)}</section><section class="platform-panel platform-registry-secondary"><header><div><h2>Applications using infrastructure</h2><p>Current application assignments and domain references.</p></div></header>${applicationTable(state)}</section>`;
  } else body = capabilityMatrix(state);
  return `<div class="platform-screen">${navigation}${heading}<div class="platform-disclosure-row">${disclosure}</div>${tabs}${state.platformForm === "application" ? appForm(state) : state.platformForm === "server" ? serverForm(state) : ""}${body}<p class="platform-source-note">${tag("LOCAL PREVIEW", "gold")} Domain ownership, repository access, and server connectivity have not been verified.</p></div>`;
}
