/**
 * Master Primitive Registry derived from the user supplied TLPS inventory.
 * Entries marked planned/required are catalog commitments, not implemented exports.
 */
export type PrimitiveRegistryStatus = "implemented" | "planned" | "required-foundation";
export type PrimitiveRegistryLayer =
  | "foundation"
  | "generic-ui"
  | "governance"
  | "domain"
  | "workflow"
  | "evidence"
  | "generative"
  | "composite"
  | "template"
  | "platform-foundation";
export interface PrimitiveRegistryItem {
  name: string;
  status: PrimitiveRegistryStatus;
  relatedExistingExport?: string;
}
export interface PrimitiveRegistryCategory {
  number: number;
  title: string;
  layer: PrimitiveRegistryLayer;
  canonicalPackage: string | null;
  status: PrimitiveRegistryStatus | "partial";
  items: PrimitiveRegistryItem[];
}

export const canonicalPackageBoundaries = [
  "@maataa/tokens",
  "@maataa/primitives",
  "@maataa/ui",
  "@tlps/domain-primitives",
  "@tlps/workflow-primitives",
  "@tlps/evidence-primitives",
  "@tlps/generative-primitives",
  "@tlps/composites",
  "@tlps/templates",
] as const;
export const canonicalPackageBoundaryStatus =
  "packages-extracted-with-canvas-and-3d-domain-surfaces" as const;

const registrySeed = [
  {
    number: 1,
    title: "Foundation / layout primitives",
    layer: "foundation",
    canonicalPackage: "@maataa/primitives",
    items: [
      { name: "Box", status: "implemented" },
      { name: "Container", status: "implemented" },
      { name: "Section", status: "planned", relatedExistingExport: "FormSection" },
      { name: "Stack", status: "implemented" },
      { name: "Inline", status: "implemented" },
      { name: "Flex", status: "implemented" },
      { name: "Grid", status: "implemented" },
      { name: "Columns", status: "planned" },
      { name: "Cluster", status: "planned" },
      { name: "Split", status: "planned" },
      { name: "Spacer", status: "implemented" },
      { name: "Divider", status: "implemented" },
      { name: "Surface", status: "planned", relatedExistingExport: "Panel" },
      { name: "Panel", status: "planned" },
      { name: "Card", status: "implemented" },
      { name: "Inset", status: "planned" },
      { name: "ScrollArea", status: "implemented" },
      { name: "Sticky", status: "planned" },
      { name: "AspectRatio", status: "implemented" },
      { name: "SafeArea", status: "planned", relatedExistingExport: "AppShell responsive layout" },
      { name: "Portal", status: "implemented" },
      { name: "Overlay", status: "planned" },
      { name: "Backdrop", status: "planned" },
      { name: "VisuallyHidden", status: "implemented" },
      { name: "ResponsiveShow", status: "planned" },
      { name: "ResponsiveHide", status: "planned" },
    ],
  },
  {
    number: 2,
    title: "Typography primitives",
    layer: "foundation",
    canonicalPackage: "@maataa/primitives",
    items: [
      { name: "Text", status: "planned" },
      { name: "Heading", status: "planned" },
      { name: "Label", status: "planned" },
      { name: "Caption", status: "planned" },
      { name: "Eyebrow", status: "planned" },
      { name: "Lead", status: "planned" },
      { name: "Paragraph", status: "planned" },
      { name: "Code", status: "planned" },
      { name: "Number", status: "planned" },
      { name: "Currency", status: "planned" },
      { name: "Percentage", status: "planned" },
      { name: "DateText", status: "planned" },
      { name: "TimeText", status: "planned" },
      { name: "Truncate", status: "planned" },
      { name: "ClampText", status: "planned" },
      { name: "RichText", status: "planned" },
      { name: "Markdown", status: "planned" },
      { name: "Link", status: "planned" },
      { name: "ExternalLink", status: "planned" },
    ],
  },
  {
    number: 3,
    title: "Navigation primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "AppShell", status: "implemented" },
      { name: "TopBar", status: "planned", relatedExistingExport: "TopNav" },
      { name: "SideNav", status: "planned", relatedExistingExport: "Sidebar" },
      { name: "BottomNav", status: "planned" },
      { name: "NavItem", status: "planned" },
      { name: "NavGroup", status: "planned" },
      { name: "Breadcrumb", status: "implemented" },
      { name: "Tabs", status: "implemented" },
      { name: "Tab", status: "planned", relatedExistingExport: "Tabs" },
      { name: "SegmentedControl", status: "planned" },
      { name: "Stepper", status: "planned" },
      { name: "Pagination", status: "implemented" },
      { name: "BackButton", status: "planned" },
      { name: "ForwardButton", status: "planned" },
      { name: "RouteLink", status: "planned" },
      { name: "DeepLink", status: "planned" },
      { name: "WorkspaceSwitcher", status: "planned" },
      { name: "ProjectSwitcher", status: "planned" },
      { name: "ContextSwitcher", status: "planned" },
      { name: "CommandPalette", status: "planned" },
      { name: "QuickLauncher", status: "planned" },
      { name: "MoreMenu", status: "planned" },
    ],
  },
  {
    number: 4,
    title: "Action primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Button", status: "implemented" },
      { name: "IconButton", status: "implemented" },
      { name: "SplitButton", status: "planned" },
      { name: "CommandButton", status: "planned" },
      { name: "PrimaryAction", status: "planned" },
      { name: "SecondaryAction", status: "planned" },
      { name: "DangerAction", status: "planned" },
      { name: "GhostButton", status: "planned" },
      { name: "FAB", status: "implemented" },
      { name: "ActionBar", status: "planned" },
      { name: "ActionTray", status: "planned" },
      { name: "ActionSheet", status: "planned" },
      { name: "BulkActionBar", status: "planned" },
      { name: "ApproveButton", status: "planned" },
      { name: "RejectButton", status: "planned" },
      { name: "RequestChangesButton", status: "planned" },
      { name: "RetryButton", status: "planned" },
      { name: "SaveButton", status: "planned" },
      { name: "PublishButton", status: "planned" },
      { name: "ExportButton", status: "planned" },
      { name: "ShareButton", status: "planned" },
    ],
  },
  {
    number: 5,
    title: "Input primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Input", status: "implemented" },
      { name: "Textarea", status: "implemented" },
      { name: "NumberInput", status: "planned" },
      { name: "CurrencyInput", status: "planned" },
      { name: "PercentageInput", status: "planned" },
      { name: "PasswordInput", status: "planned" },
      { name: "OTPInput", status: "planned" },
      { name: "SearchInput", status: "implemented" },
      { name: "PhoneInput", status: "planned" },
      { name: "EmailInput", status: "planned" },
      { name: "URLInput", status: "planned" },
      { name: "DateInput", status: "planned" },
      { name: "TimeInput", status: "planned" },
      { name: "DateTimeInput", status: "planned" },
      { name: "DateRangeInput", status: "planned" },
      { name: "FileInput", status: "implemented" },
      { name: "ImageInput", status: "planned" },
      { name: "VideoInput", status: "planned" },
      { name: "AudioInput", status: "planned" },
      { name: "ColorInput", status: "planned" },
      { name: "CoordinateInput", status: "planned" },
      { name: "AddressInput", status: "planned" },
      { name: "SignatureInput", status: "planned" },
    ],
  },
  {
    number: 6,
    title: "Selection primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Select", status: "implemented" },
      { name: "MultiSelect", status: "planned" },
      { name: "Combobox", status: "planned" },
      { name: "Autocomplete", status: "planned" },
      { name: "Checkbox", status: "implemented" },
      { name: "CheckboxGroup", status: "planned" },
      { name: "Radio", status: "implemented" },
      { name: "RadioGroup", status: "implemented" },
      { name: "Switch", status: "planned", relatedExistingExport: "Toggle" },
      { name: "Toggle", status: "implemented" },
      { name: "ToggleGroup", status: "implemented" },
      { name: "ChipSelect", status: "planned" },
      { name: "TagSelect", status: "planned" },
      { name: "RoleSelect", status: "planned" },
      { name: "WorkspaceSelect", status: "planned" },
      { name: "ProjectSelect", status: "planned" },
      { name: "VendorSelect", status: "planned" },
      { name: "CrewSelect", status: "planned" },
      { name: "TalentSelect", status: "planned" },
      { name: "LocationSelect", status: "planned" },
      { name: "EquipmentSelect", status: "planned" },
    ],
  },
  {
    number: 7,
    title: "Search / filter primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "SearchBar", status: "planned" },
      { name: "GlobalSearch", status: "planned" },
      { name: "EntitySearch", status: "planned" },
      { name: "FilterBar", status: "planned" },
      { name: "FilterChip", status: "planned" },
      { name: "FilterSheet", status: "planned" },
      { name: "AdvancedFilter", status: "planned" },
      { name: "SortMenu", status: "planned" },
      { name: "SavedView", status: "planned" },
      { name: "ViewSwitcher", status: "planned" },
      { name: "DateFilter", status: "planned" },
      { name: "StatusFilter", status: "planned" },
      { name: "RoleFilter", status: "planned" },
      { name: "OwnerFilter", status: "planned" },
      { name: "LocationFilter", status: "planned" },
      { name: "ProjectFilter", status: "planned" },
      { name: "EvidenceFilter", status: "planned" },
    ],
  },
  {
    number: 8,
    title: "Data-display primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Table", status: "planned", relatedExistingExport: "DataTable" },
      { name: "DataGrid", status: "planned", relatedExistingExport: "DataTable" },
      { name: "List", status: "planned" },
      { name: "ListItem", status: "planned" },
      { name: "DefinitionList", status: "planned" },
      { name: "KeyValue", status: "planned" },
      { name: "Metric", status: "planned" },
      { name: "MetricCard", status: "implemented" },
      { name: "StatCard", status: "planned" },
      { name: "Scorecard", status: "planned" },
      { name: "KPI", status: "planned" },
      { name: "Badge", status: "implemented" },
      { name: "Chip", status: "planned" },
      { name: "Tag", status: "planned" },
      { name: "Avatar", status: "planned" },
      { name: "AvatarStack", status: "planned" },
      { name: "Logo", status: "planned" },
      { name: "Thumbnail", status: "planned" },
      { name: "MediaCard", status: "planned" },
      { name: "EntityCard", status: "planned" },
      { name: "SummaryCard", status: "planned" },
      { name: "ComparisonCard", status: "planned" },
      { name: "DetailPanel", status: "planned" },
      { name: "InspectorPanel", status: "planned" },
    ],
  },
  {
    number: 9,
    title: "State / feedback primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "LoadingState", status: "planned" },
      { name: "Skeleton", status: "planned" },
      { name: "Spinner", status: "planned" },
      { name: "ProgressBar", status: "planned" },
      { name: "ProgressRing", status: "planned" },
      { name: "EmptyState", status: "implemented" },
      { name: "ErrorState", status: "planned" },
      { name: "SuccessState", status: "planned" },
      { name: "WarningState", status: "planned" },
      { name: "BlockedState", status: "planned" },
      { name: "OfflineState", status: "planned" },
      { name: "PermissionDenied", status: "planned" },
      { name: "NotFoundState", status: "planned" },
      { name: "MaintenanceState", status: "planned" },
      { name: "Toast", status: "implemented" },
      { name: "Snackbar", status: "planned" },
      { name: "Alert", status: "planned" },
      { name: "Banner", status: "planned" },
      { name: "InlineMessage", status: "planned" },
      { name: "StatusBadge", status: "implemented" },
      { name: "StatusDot", status: "planned" },
    ],
  },
  {
    number: 10,
    title: "Dialog / disclosure primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Modal", status: "implemented" },
      { name: "Dialog", status: "planned", relatedExistingExport: "Modal" },
      { name: "Drawer", status: "implemented" },
      { name: "Sheet", status: "implemented" },
      { name: "Popover", status: "implemented" },
      { name: "Tooltip", status: "implemented" },
      { name: "Menu", status: "implemented" },
      { name: "ContextMenu", status: "planned", relatedExistingExport: "Dropdown" },
      { name: "Dropdown", status: "implemented" },
      { name: "Accordion", status: "planned" },
      { name: "Disclosure", status: "planned" },
      { name: "ExpandablePanel", status: "planned", relatedExistingExport: "Panel" },
      { name: "ConfirmDialog", status: "planned" },
      { name: "ApprovalDialog", status: "planned" },
      { name: "RejectDialog", status: "planned" },
    ],
  },
  {
    number: 11,
    title: "Identity primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "UserAvatar", status: "planned" },
      { name: "UserCard", status: "planned" },
      { name: "ProfileCard", status: "planned" },
      { name: "IdentityBadge", status: "planned" },
      { name: "OrganisationBadge", status: "planned" },
      { name: "WorkspaceBadge", status: "planned" },
      { name: "RoleBadge", status: "planned" },
      { name: "AuthorityBadge", status: "planned" },
      { name: "DeviceBadge", status: "planned" },
      { name: "VerifiedBadge", status: "planned" },
      { name: "SessionBadge", status: "planned" },
      { name: "AccountMenu", status: "planned" },
    ],
  },
  {
    number: 12,
    title: "Authentication primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "SignInForm", status: "planned" },
      { name: "SignUpForm", status: "planned" },
      { name: "OTPForm", status: "planned" },
      { name: "PasswordResetForm", status: "planned" },
      { name: "InviteForm", status: "planned" },
      { name: "AcceptInvite", status: "planned" },
      { name: "OrganisationCreator", status: "planned" },
      { name: "OrganisationSelector", status: "planned" },
      { name: "WorkspaceSelector", status: "planned" },
      { name: "RoleSelector", status: "planned" },
      { name: "DeviceVerification", status: "planned" },
      { name: "LocationVerification", status: "planned" },
      { name: "NDAGate", status: "planned" },
      { name: "SignatureGate", status: "planned" },
      { name: "SecureAccessGate", status: "planned" },
    ],
  },
  {
    number: 13,
    title: "Permission / governance primitives",
    layer: "governance",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "PermissionGate", status: "planned" },
      { name: "RoleGate", status: "planned" },
      { name: "RouteGuard", status: "planned" },
      { name: "ActionGuard", status: "planned" },
      { name: "FieldGuard", status: "planned" },
      { name: "TenantGuard", status: "planned" },
      { name: "AuthorityMatrix", status: "planned" },
      { name: "AccessMatrix", status: "planned" },
      { name: "ApprovalGate", status: "planned" },
      { name: "PolicyGate", status: "planned" },
      { name: "SeparationOfDuties", status: "planned" },
      { name: "Delegation", status: "planned" },
      { name: "Escalation", status: "planned" },
      { name: "AccessReview", status: "planned" },
    ],
  },
  {
    number: 14,
    title: "Workspace primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "WorkspaceHeader", status: "planned" },
      { name: "WorkspaceCard", status: "planned" },
      { name: "WorkspaceSwitcher", status: "planned" },
      { name: "WorkspaceContext", status: "planned" },
      { name: "PersonalCommandCentre", status: "planned" },
      { name: "OrganisationContext", status: "planned" },
      { name: "ActivityFeed", status: "planned" },
      { name: "QuickActions", status: "planned" },
      { name: "NotificationSummary", status: "planned" },
      { name: "WorkspaceHealth", status: "planned" },
      { name: "WorkspaceMemberList", status: "planned" },
    ],
  },
  {
    number: 15,
    title: "Project primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "ProjectCard", status: "planned" },
      { name: "ProjectHeader", status: "planned" },
      { name: "ProjectSelector", status: "planned" },
      { name: "ProjectBrief", status: "planned" },
      { name: "ProjectScope", status: "planned" },
      { name: "ProjectStatus", status: "planned" },
      { name: "ProjectHealth", status: "planned" },
      { name: "ProjectProgress", status: "planned" },
      { name: "ProjectTimeline", status: "planned" },
      { name: "ProjectMilestone", status: "planned" },
      { name: "ProjectTask", status: "planned" },
      { name: "ProjectBlocker", status: "planned" },
      { name: "ProjectTeam", status: "planned" },
      { name: "ProjectActivity", status: "planned" },
      { name: "ProjectCloseout", status: "planned" },
      { name: "ProjectType", status: "planned" },
      { name: "ProjectIntake", status: "planned" },
    ],
  },
  {
    number: 16,
    title: "Task / workflow primitives",
    layer: "workflow",
    canonicalPackage: "@tlps/workflow-primitives",
    items: [
      { name: "TaskCard", status: "planned" },
      { name: "TaskList", status: "planned" },
      { name: "TaskBoard", status: "planned" },
      { name: "TaskStatus", status: "planned" },
      { name: "TaskPriority", status: "planned" },
      { name: "TaskOwner", status: "planned" },
      { name: "TaskDueDate", status: "planned" },
      { name: "TaskDependency", status: "planned" },
      { name: "TaskChecklist", status: "planned" },
      { name: "TaskComment", status: "planned" },
      { name: "WorkflowStep", status: "planned" },
      { name: "WorkflowStage", status: "planned" },
      { name: "WorkflowStatus", status: "planned" },
      { name: "WorkflowTransition", status: "planned" },
      { name: "WorkflowTemplate", status: "planned" },
      { name: "WorkflowHistory", status: "planned" },
    ],
  },
  {
    number: 17,
    title: "Creative-development primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "IdeaCard", status: "planned" },
      { name: "ConceptCard", status: "planned" },
      { name: "ResearchCard", status: "planned" },
      { name: "TreatmentCard", status: "planned" },
      { name: "ScriptCard", status: "planned" },
      { name: "ScriptReader", status: "planned" },
      { name: "ScriptVersion", status: "planned" },
      { name: "ScriptDiff", status: "planned" },
      { name: "ScriptBreakdown", status: "planned" },
      { name: "SceneCard", status: "planned" },
      { name: "SceneList", status: "planned" },
      { name: "SceneDetail", status: "planned" },
      { name: "CharacterCard", status: "planned" },
      { name: "CharacterBreakdown", status: "planned" },
      { name: "ProductionElement", status: "planned" },
      { name: "StoryboardFrame", status: "planned" },
      { name: "StoryboardBoard", status: "planned" },
      { name: "ShotCard", status: "planned" },
      { name: "ShotList", status: "planned" },
      { name: "CreativeReference", status: "planned" },
      { name: "CreativeAsset", status: "planned" },
      { name: "CreativeVersion", status: "planned" },
      { name: "CreativeApproval", status: "planned" },
    ],
  },
  {
    number: 18,
    title: "Casting primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "CastingCall", status: "planned" },
      { name: "CastingBrief", status: "planned" },
      { name: "ActorCard", status: "planned" },
      { name: "ActorProfile", status: "planned" },
      { name: "TalentCard", status: "planned" },
      { name: "TalentPortfolio", status: "planned" },
      { name: "AuditionCard", status: "planned" },
      { name: "AuditionPlayer", status: "planned" },
      { name: "AuditionSubmission", status: "planned" },
      { name: "Shortlist", status: "planned" },
      { name: "TalentComparison", status: "planned" },
      { name: "CastingDecision", status: "planned" },
      { name: "AvailabilityCard", status: "planned" },
      { name: "OfferCard", status: "planned" },
      { name: "TalentContract", status: "planned" },
      { name: "CastSchedule", status: "planned" },
      { name: "CastMessage", status: "planned" },
    ],
  },
  {
    number: 19,
    title: "Crew primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "CrewCard", status: "planned" },
      { name: "CrewProfile", status: "planned" },
      { name: "CrewRoster", status: "planned" },
      { name: "DepartmentCard", status: "planned" },
      { name: "DepartmentRoster", status: "planned" },
      { name: "HODCard", status: "planned" },
      { name: "AvailabilityStatus", status: "planned" },
      { name: "HiringRequest", status: "planned" },
      { name: "CrewShortlist", status: "planned" },
      { name: "CrewAssignment", status: "planned" },
      { name: "CrewContract", status: "planned" },
      { name: "AttendanceRecord", status: "planned" },
      { name: "Timesheet", status: "planned" },
      { name: "PerformanceRecord", status: "planned" },
      { name: "CrewMessage", status: "planned" },
    ],
  },
  {
    number: 20,
    title: "Schedule primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Calendar", status: "planned" },
      { name: "ProductionCalendar", status: "planned" },
      { name: "MasterSchedule", status: "planned" },
      { name: "ScheduleItem", status: "planned" },
      { name: "ScheduleLane", status: "planned" },
      { name: "Stripboard", status: "planned" },
      { name: "Strip", status: "planned" },
      { name: "ShootDay", status: "planned" },
      { name: "ShootDayCard", status: "planned" },
      { name: "CallTime", status: "planned" },
      { name: "CallSheet", status: "planned" },
      { name: "CallSheetSection", status: "planned" },
      { name: "CallSheetAcknowledgement", status: "planned" },
      { name: "DayOutOfDays", status: "planned" },
      { name: "Timeline", status: "planned" },
      { name: "TimelineItem", status: "planned" },
    ],
  },
  {
    number: 21,
    title: "Live-production primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "LiveStatus", status: "planned" },
      { name: "SetCommand", status: "planned" },
      { name: "SceneProgress", status: "planned" },
      { name: "ShotProgress", status: "planned" },
      { name: "AttendanceLive", status: "planned" },
      { name: "DPR", status: "planned" },
      { name: "Incident", status: "planned" },
      { name: "Delay", status: "planned" },
      { name: "Exception", status: "planned" },
      { name: "WrapStatus", status: "planned" },
      { name: "UnitStatus", status: "planned" },
      { name: "DepartmentStatus", status: "planned" },
      { name: "ProductionClock", status: "planned" },
      { name: "LiveFeed", status: "planned" },
      { name: "RuntimeCheck", status: "planned" },
    ],
  },
  {
    number: 22,
    title: "Location primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "LocationCard", status: "planned" },
      { name: "LocationProfile", status: "planned" },
      { name: "LocationGallery", status: "planned" },
      { name: "LocationMap", status: "planned", relatedExistingExport: "GeoMap" },
      { name: "LocationPin", status: "planned" },
      { name: "LocationSearch", status: "planned" },
      { name: "Recce", status: "planned" },
      { name: "RecceCapture", status: "planned" },
      { name: "RecceNote", status: "planned" },
      { name: "LocationComparison", status: "planned" },
      { name: "PermitStatus", status: "planned" },
      { name: "LocationBooking", status: "planned" },
      { name: "GeoCoordinate", status: "planned" },
      { name: "GeoFence", status: "planned" },
    ],
  },
  {
    number: 23,
    title: "Travel / logistics primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "TravelPlan", status: "planned" },
      { name: "Itinerary", status: "planned" },
      { name: "JourneyLeg", status: "planned" },
      { name: "AccommodationCard", status: "planned" },
      { name: "RoomingList", status: "planned" },
      { name: "TransportPlan", status: "planned" },
      { name: "VehicleCard", status: "planned" },
      { name: "VehicleAssignment", status: "planned" },
      { name: "DriverCard", status: "planned" },
      { name: "RoutePlan", status: "planned" },
      { name: "Dispatch", status: "planned" },
      { name: "Pickup", status: "planned" },
      { name: "Dropoff", status: "planned" },
      { name: "Shipment", status: "planned" },
      { name: "DeliveryStatus", status: "planned" },
    ],
  },
  {
    number: 24,
    title: "Equipment primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "EquipmentCard", status: "planned" },
      { name: "EquipmentCategory", status: "planned" },
      { name: "EquipmentInventory", status: "planned" },
      { name: "EquipmentKit", status: "planned" },
      { name: "EquipmentBooking", status: "planned" },
      { name: "EquipmentAssignment", status: "planned" },
      { name: "EquipmentCheckOut", status: "planned" },
      { name: "EquipmentCheckIn", status: "planned" },
      { name: "EquipmentReturn", status: "planned" },
      { name: "EquipmentCondition", status: "planned" },
      { name: "MaintenanceRecord", status: "planned" },
      { name: "Barcode", status: "planned" },
      { name: "QRScanner", status: "planned" },
    ],
  },
  {
    number: 25,
    title: "Campaign primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "CampaignCard", status: "planned" },
      { name: "CampaignBrief", status: "planned" },
      { name: "CampaignStrategy", status: "planned" },
      { name: "MarketCard", status: "planned" },
      { name: "CityCard", status: "planned" },
      { name: "MediaPlan", status: "planned" },
      { name: "ATLPlan", status: "planned" },
      { name: "BTLPlan", status: "planned" },
      { name: "OOHPlan", status: "planned" },
      { name: "DOOHPlan", status: "planned" },
      { name: "ActivationPlan", status: "planned" },
      { name: "ActivationCalendar", status: "planned" },
      { name: "ActivationCard", status: "planned" },
      { name: "FieldActivation", status: "planned" },
      { name: "SiteCard", status: "planned" },
      { name: "SiteCheckIn", status: "planned" },
      { name: "LiveActivationFeed", status: "planned" },
      { name: "LeadCard", status: "planned" },
      { name: "LeadCapture", status: "planned" },
      { name: "CampaignResult", status: "planned" },
    ],
  },
  {
    number: 26,
    title: "Marketplace primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "MarketplaceCard", status: "planned" },
      { name: "CategoryCard", status: "planned" },
      { name: "ServiceCard", status: "planned" },
      { name: "VendorCard", status: "planned" },
      { name: "VendorProfile", status: "planned" },
      { name: "VendorPortfolio", status: "planned" },
      { name: "VendorAvailability", status: "planned" },
      { name: "VendorBadge", status: "planned" },
      { name: "VendorRating", status: "planned" },
      { name: "VendorComparison", status: "planned" },
      { name: "CapabilityPack", status: "planned" },
      { name: "ServiceSKU", status: "planned" },
    ],
  },
  {
    number: 27,
    title: "Procurement primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "RFQ", status: "planned" },
      { name: "RFQLine", status: "planned" },
      { name: "RFQRecipient", status: "planned" },
      { name: "Quote", status: "planned" },
      { name: "QuoteLine", status: "planned" },
      { name: "QuoteInbox", status: "planned" },
      { name: "QuoteComparison", status: "planned" },
      { name: "CommercialComparison", status: "planned" },
      { name: "VendorAward", status: "planned" },
      { name: "PurchaseOrder", status: "planned" },
      { name: "POLine", status: "planned" },
      { name: "DeliveryTracker", status: "planned" },
      { name: "ServiceTracker", status: "planned" },
      { name: "ProcurementStatus", status: "planned" },
    ],
  },
  {
    number: 28,
    title: "Evidence primitives",
    layer: "evidence",
    canonicalPackage: "@tlps/evidence-primitives",
    items: [
      { name: "EvidenceCard", status: "planned" },
      { name: "EvidenceCapture", status: "planned" },
      { name: "PhotoEvidence", status: "planned" },
      { name: "VideoEvidence", status: "planned" },
      { name: "AudioEvidence", status: "planned" },
      { name: "DocumentEvidence", status: "planned" },
      { name: "GPSEvidence", status: "planned" },
      { name: "TimeEvidence", status: "planned" },
      { name: "DeviceEvidence", status: "planned" },
      { name: "EvidenceMetadata", status: "planned" },
      { name: "EvidenceDetail", status: "planned" },
      { name: "EvidenceTimeline", status: "planned" },
      { name: "EvidenceLink", status: "planned" },
      { name: "BeforeAfter", status: "planned" },
      { name: "ProofCard", status: "planned" },
      { name: "EvidencePackage", status: "planned" },
      { name: "EvidenceStatus", status: "planned" },
    ],
  },
  {
    number: 29,
    title: "Provenance primitives",
    layer: "evidence",
    canonicalPackage: "@tlps/evidence-primitives",
    items: [
      { name: "SourceReference", status: "planned" },
      { name: "SourceLink", status: "planned" },
      { name: "ProvenanceRecord", status: "planned" },
      { name: "ProvenanceGraph", status: "planned" },
      { name: "Hash", status: "planned" },
      { name: "Fingerprint", status: "planned" },
      { name: "Timestamp", status: "planned" },
      { name: "Signer", status: "planned" },
      { name: "ChainOfCustody", status: "planned" },
      { name: "VerificationRecord", status: "planned" },
      { name: "EvidenceVersion", status: "planned" },
    ],
  },
  {
    number: 30,
    title: "Approval primitives",
    layer: "evidence",
    canonicalPackage: "@tlps/evidence-primitives",
    items: [
      { name: "ApprovalCard", status: "planned" },
      { name: "ApprovalInbox", status: "planned" },
      { name: "ApprovalDetail", status: "planned" },
      { name: "ApprovalStatus", status: "planned" },
      { name: "ApprovalHistory", status: "planned" },
      { name: "Approver", status: "planned" },
      { name: "ApprovalDecision", status: "planned" },
      { name: "ApprovalComment", status: "planned" },
      { name: "Approve", status: "planned" },
      { name: "Reject", status: "planned" },
      { name: "RequestChanges", status: "planned" },
      { name: "Escalate", status: "planned" },
      { name: "Delegate", status: "planned" },
    ],
  },
  {
    number: 31,
    title: "Document primitives",
    layer: "evidence",
    canonicalPackage: "@tlps/evidence-primitives",
    items: [
      { name: "DocumentCard", status: "planned" },
      { name: "DocumentViewer", status: "planned" },
      { name: "DocumentPreview", status: "planned" },
      { name: "DocumentVersion", status: "planned" },
      { name: "DocumentMetadata", status: "planned" },
      { name: "DocumentFolder", status: "planned" },
      { name: "DocumentVault", status: "planned" },
      { name: "Attachment", status: "planned" },
      { name: "PDFViewer", status: "planned" },
      { name: "SpreadsheetViewer", status: "planned" },
      { name: "PresentationViewer", status: "planned" },
      { name: "ContractViewer", status: "planned" },
      { name: "NDAViewer", status: "planned" },
      { name: "PermitViewer", status: "planned" },
    ],
  },
  {
    number: 32,
    title: "Risk primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "RiskCard", status: "planned" },
      { name: "RiskRegister", status: "planned" },
      { name: "RiskScore", status: "planned" },
      { name: "RiskSeverity", status: "planned" },
      { name: "RiskProbability", status: "planned" },
      { name: "RiskImpact", status: "planned" },
      { name: "RiskOwner", status: "planned" },
      { name: "Mitigation", status: "planned" },
      { name: "Contingency", status: "planned" },
      { name: "IssueCard", status: "planned" },
      { name: "IncidentCard", status: "planned" },
      { name: "EscalationCard", status: "planned" },
    ],
  },
  {
    number: 33,
    title: "Audit primitives",
    layer: "evidence",
    canonicalPackage: "@tlps/evidence-primitives",
    items: [
      { name: "AuditEvent", status: "planned" },
      { name: "AuditTrail", status: "planned" },
      { name: "AuditTimeline", status: "planned" },
      { name: "Actor", status: "planned" },
      { name: "Action", status: "planned" },
      { name: "Object", status: "planned" },
      { name: "Timestamp", status: "planned" },
      { name: "ChangeSet", status: "planned" },
      { name: "BeforeValue", status: "planned" },
      { name: "AfterValue", status: "planned" },
      { name: "AuditFilter", status: "planned" },
      { name: "AuditExport", status: "planned" },
    ],
  },
  {
    number: 34,
    title: "Finance primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Budget", status: "planned" },
      { name: "BudgetCategory", status: "planned" },
      { name: "BudgetLine", status: "planned" },
      { name: "Estimate", status: "planned" },
      { name: "EstimateLine", status: "planned" },
      { name: "CostSheet", status: "planned" },
      { name: "CostLine", status: "planned" },
      { name: "Commitment", status: "planned" },
      { name: "Actual", status: "planned" },
      { name: "Variance", status: "planned" },
      { name: "VarianceExplanation", status: "planned" },
      { name: "Expense", status: "planned" },
      { name: "ExpenseLine", status: "planned" },
      { name: "ExpenseApproval", status: "planned" },
      { name: "Invoice", status: "planned" },
      { name: "InvoiceLine", status: "planned" },
      { name: "InvoiceApproval", status: "planned" },
      { name: "Payment", status: "planned" },
      { name: "PaymentStatus", status: "planned" },
      { name: "PaymentVerification", status: "planned" },
      { name: "CashFlow", status: "planned" },
      { name: "CashPosition", status: "planned" },
      { name: "Profitability", status: "planned" },
    ],
  },
  {
    number: 35,
    title: "Commercial primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "RateCard", status: "planned" },
      { name: "Rate", status: "planned" },
      { name: "Markup", status: "planned" },
      { name: "Commission", status: "planned" },
      { name: "Tax", status: "planned" },
      { name: "GST", status: "planned" },
      { name: "Discount", status: "planned" },
      { name: "Subtotal", status: "planned" },
      { name: "Total", status: "planned" },
      { name: "Advance", status: "planned" },
      { name: "Balance", status: "planned" },
      { name: "Recovery", status: "planned" },
      { name: "Revenue", status: "planned" },
      { name: "Margin", status: "planned" },
    ],
  },
  {
    number: 36,
    title: "Investor primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "InvestmentOpportunity", status: "planned" },
      { name: "InvestmentProfile", status: "planned" },
      { name: "DealRoom", status: "planned" },
      { name: "Disclosure", status: "planned" },
      { name: "DueDiligenceItem", status: "planned" },
      { name: "FundingRequirement", status: "planned" },
      { name: "FundingRound", status: "planned" },
      { name: "Tranche", status: "planned" },
      { name: "InvestorReport", status: "planned" },
      { name: "InvestorEvidence", status: "planned" },
      { name: "CapitalAccount", status: "planned" },
      { name: "ReturnMetric", status: "planned" },
    ],
  },
  {
    number: 37,
    title: "Rights / distribution primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Right", status: "planned" },
      { name: "RightsWindow", status: "planned" },
      { name: "Territory", status: "planned" },
      { name: "Platform", status: "planned" },
      { name: "ReleaseWindow", status: "planned" },
      { name: "DistributionChannel", status: "planned" },
      { name: "License", status: "planned" },
      { name: "RevenueWindow", status: "planned" },
      { name: "DistributionReport", status: "planned" },
      { name: "RecoupmentWaterfall", status: "planned" },
      { name: "WaterfallTier", status: "planned" },
      { name: "RecoveryPosition", status: "planned" },
      { name: "InvestorReturn", status: "planned" },
    ],
  },
  {
    number: 38,
    title: "Event primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "EventCard", status: "planned" },
      { name: "EventJourney", status: "planned" },
      { name: "EventTimeline", status: "planned" },
      { name: "RunOfShow", status: "planned" },
      { name: "RunOfShowItem", status: "planned" },
      { name: "VenueCard", status: "planned" },
      { name: "VenuePlan", status: "planned" },
      { name: "GuestCard", status: "planned" },
      { name: "GuestList", status: "planned" },
      { name: "GuestStatus", status: "planned" },
      { name: "HospitalityItem", status: "planned" },
      { name: "EventMilestone", status: "planned" },
    ],
  },
  {
    number: 39,
    title: "Wedding primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "WeddingJourney", status: "planned" },
      { name: "WeddingEvent", status: "planned" },
      { name: "WeddingRitual", status: "planned" },
      { name: "WeddingVendor", status: "planned" },
      { name: "WeddingBoard", status: "planned" },
      { name: "WeddingTimeline", status: "planned" },
      { name: "WeddingDecision", status: "planned" },
      { name: "WeddingBudget", status: "planned" },
      { name: "AIWeddingProducer", status: "planned" },
    ],
  },
  {
    number: 40,
    title: "Spatial primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Canvas", status: "implemented" },
      { name: "SpatialCanvas", status: "implemented" },
      { name: "FloorPlan", status: "planned", relatedExistingExport: "VenueFloorPlan" },
      { name: "Layout", status: "planned" },
      { name: "Layer", status: "planned" },
      { name: "Object", status: "planned" },
      { name: "ObjectLibrary", status: "planned" },
      { name: "Grid", status: "planned" },
      { name: "Ruler", status: "planned" },
      { name: "Dimension", status: "planned" },
      { name: "Coordinate", status: "planned" },
      { name: "Scale", status: "planned" },
      { name: "Snap", status: "planned" },
      { name: "Guide", status: "planned" },
      { name: "Zone", status: "planned" },
      { name: "Path", status: "planned" },
      { name: "Seat", status: "planned" },
      { name: "Booth", status: "planned" },
      { name: "Stage", status: "planned" },
      { name: "Structure", status: "planned" },
      { name: "AssetPlacement", status: "planned" },
      { name: "Annotation", status: "planned" },
    ],
  },
  {
    number: 41,
    title: "3D / simulation primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Scene3D", status: "implemented" },
      { name: "Model3D", status: "implemented" },
      { name: "Camera3D", status: "implemented" },
      { name: "OrbitControl", status: "implemented" },
      { name: "TransformControl", status: "implemented" },
      { name: "Rotate", status: "implemented" },
      { name: "Scale", status: "implemented" },
      { name: "Translate", status: "implemented" },
      { name: "Material", status: "implemented" },
      { name: "Lighting", status: "implemented" },
      { name: "Environment", status: "implemented" },
      { name: "Simulation", status: "planned" },
      { name: "LiveSimulation", status: "planned" },
      { name: "DigitalTwin", status: "planned" },
      { name: "FilmTwin", status: "planned" },
      { name: "Viewport", status: "implemented" },
      { name: "Snapshot", status: "implemented" },
    ],
  },
  {
    number: 42,
    title: "Composer primitives",
    layer: "composite",
    canonicalPackage: "@tlps/composites",
    items: [
      { name: "BoardComposer", status: "planned" },
      { name: "Board", status: "planned" },
      { name: "BoardSection", status: "planned" },
      { name: "Frame", status: "planned" },
      { name: "FrameGrid", status: "planned" },
      { name: "ImageFrame", status: "planned" },
      { name: "TextFrame", status: "planned" },
      { name: "MetricFrame", status: "planned" },
      { name: "ComparisonFrame", status: "planned" },
      { name: "TimelineFrame", status: "planned" },
      { name: "Moodboard", status: "planned" },
      { name: "PresentationStudio", status: "planned" },
      { name: "Slide", status: "planned" },
      { name: "SlideLayout", status: "planned" },
      { name: "SlideBlock", status: "planned" },
    ],
  },
  {
    number: 43,
    title: "Generative-input primitives",
    layer: "generative",
    canonicalPackage: "@tlps/generative-primitives",
    items: [
      { name: "PromptBox", status: "planned" },
      { name: "PromptTemplate", status: "planned" },
      { name: "PromptHistory", status: "planned" },
      { name: "ContextPicker", status: "planned" },
      { name: "SourcePicker", status: "planned" },
      { name: "EvidencePicker", status: "planned" },
      { name: "ProjectContextPicker", status: "planned" },
      { name: "RoleContextPicker", status: "planned" },
      { name: "ModelSelector", status: "planned" },
      { name: "GenerationMode", status: "planned" },
      { name: "GenerationParameters", status: "planned" },
    ],
  },
  {
    number: 44,
    title: "Generative-action primitives",
    layer: "generative",
    canonicalPackage: "@tlps/generative-primitives",
    items: [
      { name: "Generate", status: "planned" },
      { name: "Regenerate", status: "planned" },
      { name: "GenerateVariant", status: "planned" },
      { name: "Suggest", status: "planned" },
      { name: "Recommend", status: "planned" },
      { name: "Compose", status: "planned" },
      { name: "Draft", status: "planned" },
      { name: "Expand", status: "planned" },
      { name: "Shorten", status: "planned" },
      { name: "Rewrite", status: "planned" },
      { name: "Summarize", status: "planned" },
      { name: "Explain", status: "planned" },
      { name: "Compare", status: "planned" },
      { name: "Optimize", status: "planned" },
      { name: "Breakdown", status: "planned" },
      { name: "Plan", status: "planned" },
      { name: "Forecast", status: "planned" },
      { name: "Simulate", status: "planned" },
      { name: "Visualize", status: "planned" },
      { name: "Transform", status: "planned" },
    ],
  },
  {
    number: 45,
    title: "Generative-result primitives",
    layer: "generative",
    canonicalPackage: "@tlps/generative-primitives",
    items: [
      { name: "GeneratedResult", status: "planned" },
      { name: "GeneratedCard", status: "planned" },
      { name: "GeneratedVariant", status: "planned" },
      { name: "SuggestionCard", status: "planned" },
      { name: "RecommendationCard", status: "planned" },
      { name: "InsightCard", status: "planned" },
      { name: "ForecastCard", status: "planned" },
      { name: "ConfidenceBadge", status: "planned" },
      { name: "AssumptionList", status: "planned" },
      { name: "SourceList", status: "planned" },
      { name: "EvidenceLinks", status: "planned" },
      { name: "GenerationMetadata", status: "planned" },
      { name: "GenerationVersion", status: "planned" },
      { name: "AcceptGeneration", status: "planned" },
      { name: "RejectGeneration", status: "planned" },
      { name: "EditGeneration", status: "planned" },
      { name: "SaveGeneration", status: "planned" },
      { name: "SendForApproval", status: "planned" },
    ],
  },
  {
    number: 46,
    title: "AI primitives",
    layer: "generative",
    canonicalPackage: "@tlps/generative-primitives",
    items: [
      { name: "AICopilot", status: "planned" },
      { name: "AIChat", status: "planned" },
      { name: "Conversation", status: "planned" },
      { name: "Message", status: "planned" },
      { name: "Prompt", status: "planned" },
      { name: "Response", status: "planned" },
      { name: "ProjectContext", status: "planned" },
      { name: "SuggestedAction", status: "planned" },
      { name: "ResearchResult", status: "planned" },
      { name: "KnowledgeResult", status: "planned" },
      { name: "EvidenceAwareAnswer", status: "planned" },
      { name: "ProductionInsight", status: "planned" },
      { name: "ScheduleInsight", status: "planned" },
      { name: "BudgetInsight", status: "planned" },
      { name: "RiskInsight", status: "planned" },
      { name: "CampaignInsight", status: "planned" },
      { name: "ExecutiveInsight", status: "planned" },
    ],
  },
  {
    number: 47,
    title: "Analytics primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Metric", status: "planned" },
      { name: "Dimension", status: "planned" },
      { name: "Series", status: "planned" },
      { name: "Chart", status: "planned" },
      { name: "BarChart", status: "implemented" },
      { name: "LineChart", status: "implemented" },
      { name: "AreaChart", status: "implemented" },
      { name: "PieChart", status: "planned" },
      { name: "DonutChart", status: "implemented" },
      { name: "Funnel", status: "planned" },
      { name: "Heatmap", status: "planned" },
      { name: "Trend", status: "planned" },
      { name: "Benchmark", status: "planned" },
      { name: "KPI", status: "planned" },
      { name: "KPIGroup", status: "planned" },
      { name: "Dashboard", status: "planned" },
      { name: "AnalyticsFilter", status: "planned" },
      { name: "DateRange", status: "planned" },
      { name: "Drilldown", status: "planned" },
      { name: "Report", status: "planned" },
    ],
  },
  {
    number: 48,
    title: "Forecast primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "Forecast", status: "planned" },
      { name: "Scenario", status: "planned" },
      { name: "ScenarioSelector", status: "planned" },
      { name: "Baseline", status: "planned" },
      { name: "BestCase", status: "planned" },
      { name: "WorstCase", status: "planned" },
      { name: "Assumption", status: "planned" },
      { name: "Projection", status: "planned" },
      { name: "VarianceForecast", status: "planned" },
      { name: "ConfidenceInterval", status: "planned" },
      { name: "ForecastExplanation", status: "planned" },
    ],
  },
  {
    number: 49,
    title: "Communication primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "Notification", status: "planned" },
      { name: "NotificationCentre", status: "planned" },
      { name: "Message", status: "planned" },
      { name: "Chat", status: "planned" },
      { name: "Thread", status: "planned" },
      { name: "DirectMessage", status: "planned" },
      { name: "Mention", status: "planned" },
      { name: "Comment", status: "planned" },
      { name: "Reply", status: "planned" },
      { name: "Attachment", status: "planned" },
      { name: "Broadcast", status: "planned" },
      { name: "Announcement", status: "planned" },
      { name: "CommunicationBoard", status: "planned" },
      { name: "Presence", status: "planned" },
      { name: "UnreadBadge", status: "planned" },
    ],
  },
  {
    number: 50,
    title: "Support primitives",
    layer: "domain",
    canonicalPackage: "@tlps/domain-primitives",
    items: [
      { name: "SupportAgent", status: "planned" },
      { name: "HelpCard", status: "planned" },
      { name: "FAQ", status: "planned" },
      { name: "SupportTicket", status: "planned" },
      { name: "IssueReporter", status: "planned" },
      { name: "Feedback", status: "planned" },
      { name: "Diagnostic", status: "planned" },
      { name: "RuntimeHealth", status: "planned" },
      { name: "ObservabilityCard", status: "planned" },
    ],
  },
  {
    number: 51,
    title: "Offline / sync primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "OnlineStatus", status: "planned" },
      { name: "OfflineStatus", status: "planned" },
      { name: "SyncStatus", status: "planned" },
      { name: "SyncQueue", status: "planned" },
      { name: "QueuedAction", status: "planned" },
      { name: "PendingUpload", status: "planned" },
      { name: "SyncConflict", status: "planned" },
      { name: "ConflictResolver", status: "planned" },
      { name: "Retry", status: "planned" },
      { name: "LastSynced", status: "planned" },
      { name: "LocalDraft", status: "planned" },
      { name: "OfflineBanner", status: "planned" },
    ],
  },
  {
    number: 52,
    title: "Settings primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "SettingsSection", status: "planned" },
      { name: "SettingsRow", status: "planned" },
      { name: "Preference", status: "planned" },
      { name: "LanguageSelector", status: "planned" },
      { name: "LipiSelector", status: "planned" },
      { name: "ThemeSelector", status: "planned" },
      { name: "AppearanceSetting", status: "planned" },
      { name: "NotificationSetting", status: "planned" },
      { name: "PrivacySetting", status: "planned" },
      { name: "SecuritySetting", status: "planned" },
      { name: "FeatureFlag", status: "planned" },
      { name: "IntegrationSetting", status: "planned" },
    ],
  },
  {
    number: 53,
    title: "Admin primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "APIKey", status: "planned" },
      { name: "APIKeyList", status: "planned" },
      { name: "Webhook", status: "planned" },
      { name: "WebhookEvent", status: "planned" },
      { name: "WebhookDelivery", status: "planned" },
      { name: "Integration", status: "planned" },
      { name: "IntegrationCard", status: "planned" },
      { name: "FeatureFlag", status: "planned" },
      { name: "DataRetentionRule", status: "planned" },
      { name: "AuditLog", status: "planned" },
      { name: "AdminAction", status: "planned" },
      { name: "SystemHealth", status: "planned" },
    ],
  },
  {
    number: 54,
    title: "Export primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "ExportMenu", status: "planned" },
      { name: "ExportJob", status: "planned" },
      { name: "ShareLink", status: "planned" },
      { name: "Download", status: "planned" },
      { name: "Print", status: "planned" },
      { name: "PDFExport", status: "planned" },
      { name: "CSVExport", status: "planned" },
      { name: "JSONExport", status: "planned" },
      { name: "PresentationExport", status: "planned" },
      { name: "EvidencePackExport", status: "planned" },
      { name: "AuditExport", status: "planned" },
      { name: "ReportExport", status: "planned" },
    ],
  },
  {
    number: 55,
    title: "Mobile-specific primitives",
    layer: "generic-ui",
    canonicalPackage: "@maataa/ui",
    items: [
      { name: "MobileShell", status: "planned" },
      { name: "MobileHeader", status: "planned" },
      { name: "MobileBottomNav", status: "planned" },
      { name: "MobileFAB", status: "planned" },
      { name: "SwipeAction", status: "planned" },
      { name: "PullToRefresh", status: "planned" },
      { name: "BottomSheet", status: "planned" },
      { name: "MobileDrawer", status: "planned" },
      { name: "CameraCapture", status: "planned" },
      { name: "GeoCapture", status: "planned" },
      { name: "QRScanner", status: "planned" },
      { name: "SignaturePad", status: "planned" },
      { name: "OfflineIndicator", status: "planned" },
      { name: "SyncIndicator", status: "planned" },
      { name: "SafeArea", status: "planned", relatedExistingExport: "AppShell responsive layout" },
    ],
  },
  {
    number: 56,
    title: "System/error primitives",
    layer: "template",
    canonicalPackage: "@tlps/templates",
    items: [
      { name: "Forbidden403", status: "planned" },
      {
        name: "NotFound404",
        status: "planned",
        relatedExistingExport: "apps/admin-template system page template",
      },
      {
        name: "ServerError500",
        status: "planned",
        relatedExistingExport: "apps/admin-template system page template",
      },
      {
        name: "Maintenance",
        status: "planned",
        relatedExistingExport: "apps/admin-template system page template",
      },
      { name: "OfflineFallback", status: "planned" },
      { name: "SessionExpired", status: "planned" },
    ],
  },
  {
    number: 57,
    title: "Still-missing production primitives / foundations",
    layer: "platform-foundation",
    canonicalPackage: null,
    items: [
      { name: "RealAPIClient", status: "required-foundation" },
      { name: "WorkflowEngine", status: "required-foundation" },
      { name: "TenantIsolation", status: "required-foundation" },
      { name: "MFA", status: "required-foundation" },
      { name: "SSO", status: "required-foundation" },
      { name: "Passkey", status: "required-foundation" },
      { name: "RAGRuntime", status: "required-foundation" },
      { name: "ModelGovernance", status: "required-foundation" },
      { name: "ComplianceEngine", status: "required-foundation" },
      { name: "Billing", status: "required-foundation" },
      { name: "Entitlement", status: "required-foundation" },
      { name: "Quota", status: "required-foundation" },
      { name: "E-Signature", status: "required-foundation" },
      { name: "PaymentGateway", status: "required-foundation" },
      { name: "AccountingAdapter", status: "required-foundation" },
      { name: "TaxEngine", status: "required-foundation" },
      { name: "TrustedTimestamp", status: "required-foundation" },
      { name: "DataResidency", status: "required-foundation" },
      { name: "AccessReview", status: "required-foundation" },
      { name: "SeparationOfDuties", status: "required-foundation" },
      { name: "SCIM", status: "required-foundation" },
      { name: "WebhookGuarantee", status: "required-foundation" },
      { name: "BackupRestore", status: "required-foundation" },
      { name: "DisasterRecovery", status: "required-foundation" },
      { name: "RateLimiter", status: "required-foundation" },
      { name: "WAF", status: "required-foundation" },
      { name: "OperationalMonitoring", status: "required-foundation" },
    ],
  },
] satisfies Array<Omit<PrimitiveRegistryCategory, "status">>;

export const masterPrimitiveRegistry: PrimitiveRegistryCategory[] = registrySeed.map((category) => {
  const statuses = new Set(category.items.map((item) => item.status));
  const status = statuses.size === 1 ? category.items[0].status : "partial";
  return { ...category, status };
});
export const masterPrimitiveRegistryItemCount = masterPrimitiveRegistry.reduce(
  (total, category) => total + category.items.length,
  0,
);
export function findPrimitiveRegistryItem(name: string) {
  return masterPrimitiveRegistry.flatMap((category) =>
    category.items.filter((item) => item.name === name).map((item) => ({ ...item, category })),
  );
}
export function getPrimitiveRegistryCoverage() {
  const items = masterPrimitiveRegistry.flatMap((category) => category.items);
  return {
    total: items.length,
    implemented: items.filter((item) => item.status === "implemented").length,
    planned: items.filter((item) => item.status === "planned").length,
    requiredFoundations: items.filter((item) => item.status === "required-foundation").length,
  };
}
