/**
 * @maataa/ui/navigation/AppShell
 * Responsive application frame for workspace navigation and page content.
 */

import React, { useEffect, useId, useRef, useState } from "react";
import { colorTokens } from "../tokens";
import { Sidebar, type SidebarProps } from "./Sidebar";

export type AppShellNavigationPosition = "left" | "right" | "top" | "folded";
export type AppShellRegionPosition = "above" | "below";

export interface AppShellProps {
  /** Top-level brand and actions, spanning the full application frame. */
  topNav?: React.ReactNode;
  /** Navigation rail. A `Sidebar` receives the selected orientation and collapsed state. */
  sidebar?: React.ReactNode;
  /** Page-level tools, such as filters or create actions. */
  toolbar?: React.ReactNode;
  /** Persistent application footer. */
  footer?: React.ReactNode;
  /** Main page content. */
  children: React.ReactNode;
  /** Whether the frame fills the viewport height. @default true */
  fullHeight?: boolean;
  /** Navigation placement and initial density. @default "left" */
  navigationPosition?: AppShellNavigationPosition;
  /** Initial desktop collapsed state. Folded placement always starts collapsed. */
  navigationCollapsed?: boolean;
  /** Show a desktop control for folding and unfolding navigation. @default true */
  collapsible?: boolean;
  /** Position the toolbar relative to page content. @default "above" */
  toolbarPosition?: AppShellRegionPosition;
  /** Position the footer relative to page content. @default "below" */
  footerPosition?: AppShellRegionPosition;
  /** Accessible label for the navigation controls. @default "Primary navigation" */
  navigationLabel?: string;
  /** Optional id for the main landmark. A unique id is generated by default. */
  mainId?: string;
  /** Additional class for the outer frame. */
  className?: string;
  /** Additional styles for the outer frame. */
  style?: React.CSSProperties;
}

const shellStyles = `
.maataa-app-shell{position:relative;display:flex;flex-direction:column;min-width:0;min-height:0;color:${colorTokens.text.primary};background:${colorTokens.background.secondary};font-family:inherit}
.maataa-app-shell__skip{position:absolute;z-index:1100;top:8px;left:8px;padding:10px 14px;border-radius:6px;color:${colorTokens.background.primary};background:${colorTokens.background.inverse};transform:translateY(-160%)}
.maataa-app-shell__skip:focus{transform:translateY(0)}
.maataa-app-shell__top{display:flex;align-items:center;min-width:0;border-bottom:1px solid ${colorTokens.border.primary};background:${colorTokens.background.primary}}
.maataa-app-shell__topnav{flex:1;min-width:0}
.maataa-app-shell__toggle{display:inline-flex;align-items:center;justify-content:center;flex:0 0 40px;width:40px;height:40px;margin:0 8px;border:1px solid ${colorTokens.border.primary};border-radius:6px;color:${colorTokens.text.primary};background:${colorTokens.background.primary};cursor:pointer}
.maataa-app-shell__toggle:hover{background:${colorTokens.background.tertiary}}
.maataa-app-shell__toggle:focus-visible,.maataa-app-shell__skip:focus-visible{outline:3px solid ${colorTokens.interactive.primary};outline-offset:2px}
.maataa-app-shell__toggle svg{width:18px;height:18px}
.maataa-app-shell__desktop-toggle{display:inline-flex}
.maataa-app-shell__mobile-toggle{display:none}
.maataa-app-shell__frame{position:relative;display:flex;flex:1;min-width:0;min-height:0}
.maataa-app-shell__navigation{z-index:10;display:flex;flex:0 0 auto;min-width:0;min-height:0;overflow:auto;background:${colorTokens.background.primary}}
.maataa-app-shell__navigation[data-position="left"],.maataa-app-shell__navigation[data-position="folded"]{border-right:1px solid ${colorTokens.border.primary}}
.maataa-app-shell__navigation[data-position="right"]{order:2;border-left:1px solid ${colorTokens.border.primary}}
.maataa-app-shell__navigation[data-position="top"]{order:0;flex:0 0 auto;width:100%;min-height:0;border-bottom:1px solid ${colorTokens.border.primary}}
.maataa-app-shell__frame[data-position="top"]{flex-direction:column}
.maataa-app-shell__content{display:flex;flex:1;flex-direction:column;min-width:0;min-height:0;overflow:auto}
.maataa-app-shell__toolbar{flex:0 0 auto}
.maataa-app-shell__main{flex:1;min-width:0;min-height:0;outline:none}
.maataa-app-shell__footer{flex:0 0 auto}
.maataa-app-shell__backdrop{display:none}
@media(max-width:760px){
 .maataa-app-shell{height:auto!important;overflow:visible}
 .maataa-app-shell[data-full-height="true"]{min-height:100dvh}
 .maataa-app-shell__top{position:sticky;top:0;z-index:20;min-height:56px}
 .maataa-app-shell__desktop-toggle{display:none}
 .maataa-app-shell__mobile-toggle{display:inline-flex}
 .maataa-app-shell__frame{min-height:calc(100dvh - 57px);overflow:visible}
 .maataa-app-shell__navigation{position:fixed;z-index:1001;top:0;bottom:0;left:0;width:min(320px,84vw);max-width:calc(100vw - 36px);min-height:100dvh;overflow:auto;box-shadow:0 12px 36px rgba(61,40,23,.18);transition:transform .22s cubic-bezier(.2,.75,.25,1)}
 .maataa-app-shell__navigation[data-position="right"]{right:0;left:auto;transform:translateX(105%)}
 .maataa-app-shell__navigation[data-position="left"],.maataa-app-shell__navigation[data-position="folded"],.maataa-app-shell__navigation[data-position="top"]{transform:translateX(-105%)}
 .maataa-app-shell__navigation[data-open="true"]{transform:translateX(0)}
 .maataa-app-shell__navigation[data-position="top"]{width:min(320px,84vw);border-right:1px solid ${colorTokens.border.primary};border-bottom:0}
 .maataa-app-shell__backdrop[data-open="true"]{position:fixed;z-index:1000;inset:0;display:block;width:100%;height:100%;border:0;background:rgba(24,18,13,.38)}
 .maataa-app-shell__content{overflow:visible}
}
@media(prefers-reduced-motion:reduce){.maataa-app-shell__navigation{transition:none}}
`;

function MenuGlyph() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      aria-hidden="true"
    >
      <path d="M4 6.5h16M4 12h16M4 17.5h16" />
    </svg>
  );
}

/**
 * Responsive shell that composes navigation, global actions, page tools,
 * content, and persistent footer regions. Existing `topNav`, `sidebar`, and
 * `children` composition remains supported.
 */
export const AppShell: React.FC<AppShellProps> = ({
  topNav,
  sidebar,
  toolbar,
  footer,
  children,
  fullHeight = true,
  navigationPosition = "left",
  navigationCollapsed = false,
  collapsible = true,
  toolbarPosition = "above",
  footerPosition = "below",
  navigationLabel = "Primary navigation",
  mainId,
  className,
  style,
}) => {
  const generatedId = useId();
  const navigationId = `maataa-navigation-${generatedId.replace(/:/g, "")}`;
  const contentId = mainId ?? `maataa-main-${generatedId.replace(/:/g, "")}`;
  const [collapsed, setCollapsed] = useState(
    navigationPosition === "folded" || navigationCollapsed
  );
  const [mobileOpen, setMobileOpen] = useState(false);
  const mobileToggleRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (!mobileOpen) return undefined;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setMobileOpen(false);
        mobileToggleRef.current?.focus();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [mobileOpen]);

  const orientation = navigationPosition === "top" ? "horizontal" : "vertical";
  const navigationContent =
    React.isValidElement<SidebarProps>(sidebar) && sidebar.type === Sidebar
      ? React.cloneElement(sidebar, {
          collapsed: orientation === "horizontal" ? false : collapsed && !mobileOpen,
          orientation,
          label: navigationLabel,
          ...(orientation === "horizontal" ? { width: "100%" } : {}),
        })
      : sidebar;
  const shellClassName = ["maataa-app-shell", className].filter(Boolean).join(" ");
  const shellStyle: React.CSSProperties = {
    height: fullHeight ? "100vh" : "100%",
    backgroundColor: colorTokens.background.secondary,
    ...style,
  };
  const toggle = (kind: "mobile" | "desktop") => (
    <button
      ref={kind === "mobile" ? mobileToggleRef : undefined}
      type="button"
      className={`maataa-app-shell__toggle maataa-app-shell__${kind}-toggle`}
      aria-label={
        kind === "mobile"
          ? mobileOpen
            ? "Close navigation"
            : "Open navigation"
          : collapsed
            ? "Expand navigation"
            : "Collapse navigation"
      }
      aria-controls={navigationId}
      aria-expanded={kind === "mobile" ? mobileOpen : !collapsed}
      onClick={() =>
        kind === "mobile" ? setMobileOpen((open) => !open) : setCollapsed((value) => !value)
      }
    >
      <MenuGlyph />
    </button>
  );

  return (
    <div
      className={shellClassName}
      style={shellStyle}
      data-navigation-position={navigationPosition}
      data-full-height={fullHeight}
    >
      <style>{shellStyles}</style>
      <a className="maataa-app-shell__skip" href={`#${contentId}`}>
        Skip to content
      </a>
      {(topNav || sidebar) && (
        <div className="maataa-app-shell__top">
          {sidebar && toggle("mobile")}
          {sidebar && collapsible && navigationPosition !== "top" && toggle("desktop")}
          {topNav && <div className="maataa-app-shell__topnav">{topNav}</div>}
        </div>
      )}
      <div className="maataa-app-shell__frame" data-position={navigationPosition}>
        {sidebar && (
          <div
            id={navigationId}
            className="maataa-app-shell__navigation"
            data-position={navigationPosition}
            data-open={mobileOpen}
          >
            {navigationContent}
          </div>
        )}
        <div className="maataa-app-shell__content">
          {footer && footerPosition === "above" && (
            <footer className="maataa-app-shell__footer">{footer}</footer>
          )}
          {toolbar && toolbarPosition === "above" && (
            <div className="maataa-app-shell__toolbar">{toolbar}</div>
          )}
          <main id={contentId} className="maataa-app-shell__main" tabIndex={-1}>
            {children}
          </main>
          {toolbar && toolbarPosition === "below" && (
            <div className="maataa-app-shell__toolbar">{toolbar}</div>
          )}
          {footer && footerPosition === "below" && (
            <footer className="maataa-app-shell__footer">{footer}</footer>
          )}
        </div>
      </div>
      {sidebar && (
        <button
          type="button"
          className="maataa-app-shell__backdrop"
          data-open={mobileOpen}
          aria-label="Close navigation"
          tabIndex={mobileOpen ? 0 : -1}
          onClick={() => setMobileOpen(false)}
        />
      )}
    </div>
  );
};

AppShell.displayName = "AppShell";
